### ISSUE TITLE
Feature request: select the only option that has TOTP configured when two solutions match one's `bw totp` search

### ISSUE THREAD

**Issue by quilicicf** [bitwarden/cli#100]
Hi, 

I have a small usability issue with the CLI that I think could be fixed pretty easily. 

I've got two GitHub account, my main one that I must secure as well as possible and a second one that I only use for tests and that does not really matter. 

The first one, `GitHub` has TOTP configured, the second one, `Github - empty` has not. 

When running `bw get totp git`, bw fails telling me:

```
More than one result was found. Try getting a specific object by `id` instead. The following objects were found:
${UUID1}
${UUID2}
```

I expected it not to fail because only one account has TOTP configured. 

This seems like a fairly simple thing to fix and I'd be happy to help if you can point me to where this is done.

Thanks,

**Comment by kspearrin** [comment]
Should be available next version. See https://github.com/bitwarden/cli/commit/268852035ab96ae838e221b4c60b4af59b3ddbf0

**Comment by quilicicf** [comment]
Noice thanks!
