### ISSUE TITLE
Syntax error on Node v4.2.6

### ISSUE THREAD

**Issue by gpanders** [bitwarden/cli#104]
Node v4.2.6 is the version packaged on Ubuntu 16.04 (which I use at work). After installing `bw` with
```console
npm install -g @bitwarden/cli
```
I get the following error when trying to run `bw`:
```
/home/greande/.local/share/npm/lib/node_modules/@bitwarden/cli/build/bw.js:366
    constructor(cryptoService, apiService, userService, tokenService, appIdService, i18nService, platformUtilsService, messagingService, setCryptoKeys = true) {
                                                                                                                                                       ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

My _guess_ is that this version of Node is too old and does not support some feature that is being used here. If that is the case, and there is a minimum Node version requirement for `bw`, can that be listed somewhere on the README?

**Comment by kspearrin** [comment]
We build with Node 10, but I think Node 6 might work. Not sure though.

**Comment by djsmith85** [comment]
Hi @gpanders , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

FYI: The current node version we use to build is 14.17 and npm v7

Regards Daniel
