### ISSUE TITLE
Automatically lock vault after a certain time

### ISSUE THREAD

**Issue by cosama** [bitwarden/cli#107]
It would increase security if it would be possible to define a time out after which a session key expires and the vault needs to be unlocked again before information can be accessed.

**Comment by kspearrin** [comment]
The CLI couldn't support this. It is not a continuous running program like other Bitwarden client apps. You are responsible for maintaining your session key. We cover this in the docs here: https://help.bitwarden.com/article/cli/#locking

**Comment by pieterdd** [comment]
It definitely can, that's a choice. If the Bitwarden CLI ran as a daemon (which has its pros and cons), then it would totally be feasible.

**Comment by pieterdd** [comment]
But more realistically, is there an easy command I can put in my `.bashrc` to automatically lock the vault if the session has been open for over x hours? It's far from airtight but it already is a little bit safer.

**Comment by Alexander-Shukaev** [comment]
Also related to my question in #232.  Does this mean that this "session key" persists forever somehow, i.e. even through machine reboots?  If yes, how (where is that cached)?  If it leaks to other applications, e.g. by means of environment variable, can it be abused only until explicit `lock` or `logout` is issued or forever until master encryption key is rotated?
