### ISSUE TITLE
`https-proxy-agent`: Machine-In-The-Middle

### ISSUE THREAD

**Issue by tukusejssirs** [bitwarden/cli#109]
I have just built `bw` from Git source code (`git clone`, `npm install`) on vanilla CentOS Stream 8.

`npm` says that it has found 1 high severity vulnerability, specifically in package `https-proxy-agent` and links this issue to [this page](https://www.npmjs.com/advisories/1184).

I think `bw` should raise the required version of `https-proxy-agent` or otherwise fix this issue.

Thanks! :)

**Comment by djsmith85** [comment]
Hi @tukusejssirs thank you for your report. As this is an older issue, I just checked and we currently use `https-proxy-agent` in version `5.0.0`, so the possible vulnerability is fixed.

Regards Daniel
