### ISSUE TITLE
Creating an organization collection item

### ISSUE THREAD

**Issue by roobert** [bitwarden/cli#110]
Hi!

I'm attempting to create a collection item. I can create an item fine using the item template.

When I amend the template with a `collectionIds: ["<my_collection_id>"]` key/value I get the following:
```
{
  "organizationId": "<my_org_id>",
  "folderId": null,
  "type": 1,
  "name": "test_name",
  "notes": "",
  "favorite": false,
  "fields": [],
  "login": {
    "uris": [],
    "username": "test_name",
    "password": "test_pass",
    "totp": ""
  },
  "secureNote": null,
  "card": null,
  "identity": null,
  "collectionIds": [
    "<my_collection_id>"
  ]
}
```
This gets accepted and the following is returned:
```
{
  "object": "item",
  "id": "<item_id>",
  "organizationId": "<my_organization_id>",
  "folderId": null,
  "type": 1,
  "name": "test_name",
  "notes": null,
  "favorite": false,
  "login": {
    "uris": [],
    "username": "test_name",
    "password": "test_pass",
    "totp": null,
    "passwordRevisionDate": null
  },
  "revisionDate": "2019-12-21T13:13:01.334Z"
}
```

I can fetch the item with `bw get item <id>` however the item is not visible in the GUI even after a sync. As you can see the `collectionsId` key is also missing.

Am I misunderstanding how to create collection items or could this be a bug?

Kind regards

**Comment by kspearrin** [comment]
With the CLI you cannot create an item with associated collections in the same call. You need to first `create` the item, and the use `bw edit item-collections <id>` with the returned id.

**Comment by roobert** [comment]
@kspearrin - Great, thank you!
