### ISSUE TITLE
Can't change an items collection from command line

### ISSUE THREAD

**Issue by tylerkarch** [bitwarden/cli#114]
Hi
I'm running the code given on the bitwarden documentation to change an items collection

`echo '["f3b1f602-0660-40db-8d94-ab6601050c5d"]' | bw encode | bw edit item-collections bef0773b-60ea-452f-870f-ab660104eed7`

The first id referring to a collection within my shared organization and the second id referring to an item within that same organization that is unassigned to a collection.

I am getting the error "Resource not found"

I can list these collections and items in the command line so the cli knows they exist. I am an admin for my organization.

Thank you

**Comment by kspearrin** [comment]
Whenever you log into the web vault, so you see this item in your personal "all items" vault listing?

**Comment by tylerkarch** [comment]
Hi.
Running `bw list items` returns the list of all items in my organization's vault of which that id can be found in there. running `bw list org-collections --organizationid <My vaults organization id>` also gives me all the collections as well.

I can also see all of these items on the webpage.

**Comment by kspearrin** [comment]
Can you email support@bitwarden.com with your user account's email address? I can then look into the data a bit more. Just direct the email to @kspearrin and I will receive it.

**Comment by tylerkarch** [comment]
Cheers. Sent an email through

**Comment by kspearrin** [comment]
@tylerkarch I got your ticket with your user account info. According to the database, your user account is not associated with access to any collections. While you can see these items in the organization admin's vault (because you are an admin), you need to assign yourself to them to be able to work with them outside of that context, like with the CLI. You can assign yourself to all collections if that is what you want. Then give it a try again.

**Comment by dubitci** [comment]
I've figured it out. For future reference assigning the collection to my user did nothing but creating a group called cli and assigning that group to my user that can modify all items made it the item collection command work

**Comment by tylerkarch** [comment]
I've figured it out. For future reference assigning the collection to my user did nothing but creating a group called cli and assigning that group to my user that can modify all items made the item collection command work again. Thank you very much for your help.
