### ISSUE TITLE
data.json location

### ISSUE THREAD

**Issue by anonymous1184** [bitwarden/cli#117]
If the `bw.json` file is next to `bw` binary it should use current directory as `BITWARDENCLI_APPDATA_DIR` (for shared environments/portability).

Of course this that makes much more sense on Windows. Still holds true if you need to access more than one account at the same time.

Checking if the file exists before looking for the envvar should do. Other option is to add a CLI option like `bw --data bw.json`.
https://github.com/bitwarden/cli/blob/fe9268fffbaaa54bad5382c121795b4896cef5aa/src/bw.ts#L77

EDIT: file name. Using the same name for the configuration and the binary makes easier run file management commands (e.g. `mv bw* foo/bar`).

**Comment by kspearrin** [comment]
Do you know how to resolve the executable's directory name? `__dirname` won't resolve properly once packaged and an executable.

**Comment by anonymous1184** [comment]
To be honest haven't touched JS in at least 3 years, yet I still enjoy to read source code I use. The issue you describe seems from to be from WebPack.

The first and the last entries in the issue [5424](https://github.com/webpack/webpack/issues/5424) have working fixes. Wish I'd have the time to properly test for myself.

**Comment by kspearrin** [comment]
The issue comes from how the packaged binary handles __dirname. See https://github.com/zeit/pkg#snapshot-filesystem

**Comment by anonymous1184** [comment]
According to the docs either `process.cwd()` or `path.dirname(process.execPath)` should work. I can setup a test bench at end of the week, if I'm not too late maybe I can be of some help, of course I need to read a bit since I haven't write anything around Electron.

A lot of apps use it now (in this particular moment I'm running Authy, Bitwarden, Min Browser, Sedja, Slack, VSCode) so it won't be wasted time :)

**Comment by kspearrin** [comment]
Looks like `process.execPath` will work. See here:
https://github.com/bitwarden/cli/commit/d91a24a8e91766a590a1e3e2506ac4d1a8f1f212

It will try to load from `./bw-data/data.json`

**Comment by anonymous1184** [comment]
Superb... is there any CI from where I can grab the executable for either Win or macOS?

**Comment by kspearrin** [comment]
https://ci.appveyor.com/project/bitwarden/cli/build/job/vbgwhqo719qyxtae/artifacts

**Comment by anonymous1184** [comment]
Not working on macOS or Windows, looks like you're using `process.execPath` and should be `path.dirname(process.execPath)`? Don't know for sure. The other option is simply `process.cwd()`. I can test Linux too after noon, right now I'm in work environments and... well, can't use the VMs for other than work-related.

**Comment by kspearrin** [comment]
Yes, you are correct. `path.dirname(process.execPath)` 

Latest commit fixes that

**Comment by anonymous1184** [comment]
Working fine in macOS and Windows. Will test in CentOS in a few, post back IF findings. Thanks a lot for the dedication and promptness.
