### ISSUE TITLE
1.9.0: the new automatic TTY detection breaks scripts

### ISSUE THREAD

**Issue by ewjoachim** [bitwarden/cli#118]
My script has the following function:
```bash
export_bw_session(){
        bw login --check || export BW_SESSION="$(bw login --raw)"
        bw unlock --check || export BW_SESSION="$(bw unlock --raw)"
        bw sync
}

```
This worked prior to 1.9.0. After upgrading, it stopped working: `bw login --raw` and `bw login --raw` now won't interactively ask for login/password

If we take the unlock case, I'd say it's because this line:
https://github.com/bitwarden/cli/blame/e7450d27e468f0e68fe5b75f9c52ffa952185484/src/commands/unlock.command.ts#L18

I would guess the problem is that unlock needs to disable reading from stdin if **stdin** is not a tty, but as of today, it's based on whether **stdout** is a tty or not.

Can you confirm ? Am I doing it wrong ? What should be the correct way to use ``--raw`` if not in `BW_SESSION="$(bw login --raw)" ?
`

**Comment by pyrr** [comment]
Yep. This also broke my bash wrapper. Any possible work around ?

**Comment by ewjoachim** [comment]
Adding: Testing should probably be based on stdin and stderr. But not stdout.

**Comment by kspearrin** [comment]
I have updated the next hotfix to only skip interaction if `--nointeraction` flag is passed in.

**Comment by ewjoachim** [comment]
Nice, thanks !
