### ISSUE TITLE
bitwarden cli in WSL

### ISSUE THREAD

**Issue by matthiasa4** [bitwarden/cli#130]
After successfully installing the Bitwarden CLI in wsl, logging in, unlocking the vault and setting the session key, a `bw list items` returns an empty list. Doing the same in Powershell returns all the items in my vault. 

Is WSL supported? Any configuration steps I have missed?

**Comment by kspearrin** [comment]
I see no reason why WSL would not work. It may be an issue as to where it is referencing your data.json database file.

Here is the code for that:

```
        const relativeDataDir = path.join(path.dirname(process.execPath), 'bw-data');
        if (fs.existsSync(relativeDataDir)) {
            p = relativeDataDir;
        } else if (process.env.BITWARDENCLI_APPDATA_DIR) {
            p = path.resolve(process.env.BITWARDENCLI_APPDATA_DIR);
        } else if (process.platform === 'darwin') {
            p = path.join(process.env.HOME, 'Library/Application Support/Bitwarden CLI');
        } else if (process.platform === 'win32') {
            p = path.join(process.env.APPDATA, 'Bitwarden CLI');
        } else if (process.env.XDG_CONFIG_HOME) {
            p = path.join(process.env.XDG_CONFIG_HOME, 'Bitwarden CLI');
        } else {
            p = path.join(process.env.HOME, '.config/Bitwarden CLI');
        }
```

On Linux processes, it will reference `path.join(process.env.HOME, '.config/Bitwarden CLI')`. I am not sure how WSL is detected here.

**Comment by matthiasa4** [comment]
I can see the `data.json` file sitting in `~/.config/Bitwarden CLI`. Any steps I can try to debug?

**Comment by kspearrin** [comment]
Does it contain any data?

**Comment by matthiasa4** [comment]
A `cat ~/.config/Bitwarden\ CLI/data.json | jq 'keys` prints the following:
```
[
  "__PROTECTED__key",
  "accessToken",
  "appId",
  "encKey",
  "encPrivateKey",
  "installedVersion",
  "kdf",
  "kdfIterations",
  "keyHash",
  "refreshToken",
  "userEmail",
  "userId"
]
```
