### ISSUE TITLE
bw get username <name> returns more than one result and does not match exact <name>

### ISSUE THREAD

**Issue by mstoetzer** [bitwarden/cli#151]
Following entries exist:

- Name: `foobar.example.com`
- Name: `foobar2.example.com` 
- Name: `host1.foobar.example.com`
- Name: `host2.foobar.example.com` 

`bw get password foobar.example.com` gives 

```
More than one result was found. Try getting a specific object by `id` instead. The following objects were found:
9aasdfagafgsdf-asdf-45534-00ccfc52
f1asdfadhsdfhf4-b25c-abfa007c8ed1
fadhsdfhf4-b2asdf5c-abfa00asdfed1
```

I would expect `bw get password foobar.example.com` gives exact one entry.

What do you think?

**Comment by mstoetzer** [comment]
Is the problem here?

https://github.com/bitwarden/cli/blob/master/src/commands/get.command.ts#L118

**Comment by cscharf** [comment]
Hi @mstoetzer , very sorry for the late reply. It looks like you're using the `get password` command passing in a search string, which in turn actually calls the following routine in `jslib`, [searchCiphersBasic](https://github.com/bitwarden/jslib/blob/master/src/services/search.service.ts#L142), which then in turn, based on the entries you have listed above and the value you're passing in, would match on [line 157](https://github.com/bitwarden/jslib/blob/master/src/services/search.service.ts#L157) based on the `login.url.toLowerCase().indexOf(query) > -1` test.

We can absolutely consider an enhancement request to modify or enhance the search functionality used here in the CLI, and if that would be desired, please consider searching through and/or posting to the [Bitwarden Community Forums](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Going to close this for now, but please feel free to reach out if you have any other questions/concerns about the current behavior. Thanks!
