### ISSUE TITLE
Adding and Item to collection after create

### ISSUE THREAD

**Issue by Joevdwalt** [bitwarden/cli#153]
Hi, 

From the documentation I am not able to figure out how to add an item I have created to a specific collection. I might just be an idiot, 

I think I should be using 
```bash 
bw edit item-collection 
```

But confused as to the parameters I should be passing?

**Comment by kspearrin** [comment]
Parameters should be the id of the item and piping in a base64 encoded JSON array of collection ids.

This is shown in the examples in the docs:
https://bitwarden.com/help/article/cli/#edit

```
echo '["86544cd3-7e07-42bb-ba3c-e7f59852acaa","ae8c6c9e-26de-442c-b63b-3e28ef61d72d"]' | \
    bw encode | bw edit item-collections db71c8d6-3e69-4593-a6de-505e94966290
```

**Comment by Joevdwalt** [comment]
OK thanks. I did read the docs, but that wasn't immediately apparent. Maybe consider adding exactly this to the docs.

> Parameters should be the id of the item and piping in a base64 encoded JSON array of collection ids.

**Comment by Mubaer** [comment]
I cannot figure that out. I create an item and get the item-id "1ea0e288-e228-4a23-b5ab-ad3d00a85a30". Then I do

echo '["1435d7dd-5fd7-4fce-8c30-acd4008df2a3"]'  | .\bw.exe encode | .\bw.exe edit item-collections 1ea0e288-e228-4a23-b5ab-ad3d00a85a30

with "1435d7dd-5fd7-4fce-8c30-acd4008df2a3" being the collectionID, I get an error: ".\bw.exe : Resource not found."

When I do the same stuff with an item that already exists in a different collection, everything works fine. What am I doing wrong?

**Comment by fbreckle** [comment]
I also had this problem. I had created the secret in the organization directly. Then the secret was in the organization in the "Unassigned" collection. From there, I could not move it away in any way via the CLI.
What fixed the issue was creating the secret without organization id (so in my personal space). Then I could use the `move` command to move it to the org and collection.
