### ISSUE TITLE
Feature request: Support for Alpine Linux (musl libc)

### ISSUE THREAD

**Issue by broizter** [bitwarden/cli#155]
Would be great if this tool could natively run on Alpine Linux. Currently this is the error when you try to run it:

```
Failed to execute process './bw'. Reason:
The file './bw' does not exist or could not be executed.
```
Without knowing for sure, I'm guessing it's because Alpine Linux uses musl instead of glibc.

**Comment by Greenderella** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests/) like this one.

Please sign up on our forums and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

**Comment by jantari** [comment]
I'm running into the same issue on Alpine:

	computer:~# ls
	bw
	computer:~# stat ./bw
	  File: ./bw
	  Size: 68214259        Blocks: 192152     IO Block: 512    regular file
	Device: 2h/2d   Inode: 12384898976552988  Links: 1
	Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
	Access: 2021-07-01 14:09:52.000000000 +0000
	Modify: 2021-07-01 14:09:52.000000000 +0000
	Change: 2021-07-01 14:23:16.397523900 +0000
	computer:~# ./bw
	ash: ./bw: not found
	computer:~#

[This SE post](https://unix.stackexchange.com/questions/18061/why-does-sh-say-not-found-when-its-definitely-there) is what made me realize this is a bitwarden-cli problem and not me going crazy (I thought it was telling me the ./bw file couldn't be found)

**Comment by njhallett** [comment]
It can't locate a library:
```
testclient:~$ ldd /usr/local/bin/bw
        /lib64/ld-linux-x86-64.so.2 (0x7f25744de000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f25744de000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f257433d000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f25744de000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f2574323000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f25744de000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f25744de000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/bin/bw)
Error relocating /usr/local/bin/bw: gnu_get_libc_version: symbol not found
Error relocating /usr/local/bin/bw: __register_atfork: symbol not found
Error relocating /usr/local/bin/bw: __strdup: symbol not found
Error relocating /usr/local/bin/bw: setcontext: symbol not found
Error relocating /usr/local/bin/bw: makecontext: symbol not found
Error relocating /usr/local/bin/bw: backtrace: symbol not found
Error relocating /usr/local/bin/bw: getcontext: symbol not found
Error relocating /usr/local/bin/bw: __libc_stack_end: symbol not found
```
install:
```
sudo apk add libc6-compat gcompat
```
