### ISSUE TITLE
data.json is world readable

### ISSUE THREAD

**Issue by andsens** [bitwarden/cli#160]
It seems that data.json is world readable on Ubuntu 18.04 in `$HOME/.config/Bitwarden CLI/`
```
$ ls -al $HOME/.config/Bitwarden\ CLI 
total 724K
drwx------  2 aim aim 4.0K Aug 10 13:24 .
drwx------ 36 aim aim 4.0K Aug 26 12:34 ..
-rw-r--r--  1 aim aim 715K Aug 28 13:05 data.json
```

I am aware that all critical data is encrypted, but limiting access would reduce the attack surface if the master password were to be leaked some time in the future.

**Comment by ngdangtu-vn** [comment]
The `data.json` is under home directory. Doesn't it mean that only the user of that home directory would have the right to access it? So even if `data.json` has the world readable, can other users actually access to the path and read it?

**Comment by andsens** [comment]
> So even if data.json has the world readable, can other users actually access to the path and read it?

No, definitely not! You can just `$ cat /home/someuser/.config/private-file.json` if that file is world readable.

**Comment by ngdangtu-vn** [comment]
Ok, that's good to know. So my PR won't go waste.

**Comment by tjyang** [comment]
- My test on centos 7 show different cat result.
```
[me@bw ~]$ sudo ls  -ld  /home/bitwarden/
drwx------. 6 bitwarden bitwarden 4096 Sep 15 12:22 /home/bitwarden/
[tme@bw ~]$

[me@bw ~]$sudo ls  -l  /home/bitwarden/.config/Bitwarden\ CLI/data.json
-rw-rw-r-- 1 bitwarden bitwarden 11701 Sep 24 08:18 /home/bitwarden/.config/Bitwarden CLI/data.json
[tme@bw ~]$ cat  /home/bitwarden/.config/Bitwarden\ CLI/data.json
cat: /home/bitwarden/.config/Bitwarden CLI/data.json: Permission denied
```

**Comment by andsens** [comment]
@tjyang @ngdangtu-vn I stand corrected! My apologies, it seems I have had an incorrect image in my head on how these permissions work for 10+ years... wow. My own test on Ubuntu just confirmed what you are showing @tjyang.

**Comment by kspearrin** [comment]
So this issue can now be closed?

**Comment by tjyang** [comment]
@kspearrin, Not to nit pick, I do agree with @ngdangtu-vn  data.json file mode should not be world readable when created.

**Comment by tjyang** [comment]
@kspearrin , Thanks for the fix.
