### ISSUE TITLE
Unable to login via SSO on Linux (snap installation)

### ISSUE THREAD

**Issue by rkujawa** [bitwarden/cli#166]
I've tried using the snap-packaged `bw` to see if the SSO issue from #165 persists there, but ran into another problem.

Trying to log in via SSO with snap-packaged `bw` fails in the following way:
```
$ bw login --sso
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EPERM :::8065
    at Server.setupListenHandle [as _listen2] (net.js:1327:14)
    at listenInCluster (net.js:1375:12)
    at Server.listen (net.js:1462:7)
    at getSsoCode.Promise (/snapshot/cli/build/bw.js:24850:40)
    at new Promise (<anonymous>)
    at commands_login_command_LoginCommand.<anonymous> (/snapshot/cli/build/bw.js:24818:20)
    at Generator.next (<anonymous>)
    at login_command_awaiter (/snapshot/cli/build/bw.js:24622:71)
    at new Promise (<anonymous>)
    at login_command_awaiter (/snapshot/cli/build/bw.js:24618:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1354:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I see that it fails to spin up the web server used for `getSsoCode` with permission error. Maybe it is just an error in snap packaging that does not take the web server into account.

This is on Fedora 32 with `snapd-2.45.3.1-1.fc32.x86_64`.

**Comment by kspearrin** [comment]
Some discussion on a similar issue here: https://forum.snapcraft.io/t/fedora-32-cgroup-v2-is-not-fully-supported-yet/19295/2

**Comment by rkujawa** [comment]
The cgroups v2 warning is in my opinion not related to EPERM at all.

I decided to dig a bit deeper and indeed, as I originally suspected, this is a problem in snap packaging of bw:
```
$  sudo journalctl --output=short --follow --all | sudo /var/lib/snapd/snap/bin/snappy-debug.security scanlog
= Seccomp =
Time: Sep 22 18:26:21
Log: auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=39472 comm="bw" exe="/snap/bw/18/bw" sig=0 arch=c000003e 50(listen) compat=0 ip=0x7fbb7537c2d7 code=0x50000
Syscall: listen
Suggestion:
* add one of 'browser-support, desktop-legacy, libvirt, network-bind' to 'plugs'
```

So it means, the interface necessary for the snap package to spin up web server is missing. See:
https://snapcraft.io/docs/network-bind-interface

**Comment by kspearrin** [comment]
@rkujawa 

If you manually connect the interface, does it then work?

https://snapcraft.io/docs/interface-management

**Comment by rkujawa** [comment]
@kspearrin 

Not sure how to do that, since `bw` snap does not define the necessary plug for this to work.

```
$ sudo snap connect bw:network-bind :network-bind
error: snap "bw" has no plug named "network-bind"
```

**Comment by kspearrin** [comment]
Ok, i misunderstood. I am merging #168 which should fix it.
