### ISSUE TITLE
bw-cli sends unformatted data to stdout even when --response is used

### ISSUE THREAD

**Issue by ggiesen** [bitwarden/cli#188]
I'm trying to integrate bw-cli using a python script, and I'm having a hard time reliably getting the status of the vault. I'm attempting to use (the equivalent of):

`BW_SESSION="Q29ycmVjdEhvcnNlQmF0dGVyeVN0YXBsZQ==" bw --nointeraction --response status` to check whether the session key is valid, 

but I receive data on stdout that is not in JSON format:

1. With valid session key:
`{"success":true,"data":{"object":"template","template":{"serverUrl":"https://host.example.com","lastSync":"2020-11-19T03:39:47.693Z","userEmail":"user@example.com","userId":"ad759cd4-5218-4fff-9ca5-1b28ac228ace","status":"unlocked"}}}` <-- STDOUT
(no output to STDERR)
Exit code is 0

2. With invalid session key:
`Session key is invalid.` <-- STDOUT
`{"success":true,"data":{"object":"template","template":{"serverUrl":"https://host.example.com","lastSync":"2020-11-19T03:39:47.693Z","userEmail":"user@example.com","userId":"ad759cd4-5218-4fff-9ca5-1b28ac228ace","status":"locked"}}}` <-- STDOUT
(no output to STDERR)
Exit code is 0

3. With user logged out:
`{"success":true,"data":{"object":"template","template":{"serverUrl":"https://host.example.com","lastSync":null,"userEmail":null,"userId":null,"status":"unauthenticated"}}}` <-- STDOUT
(no output to STDERR)
Exit code is 0

I've also tried using (again, the equivalent of):

`BW_SESSION="Q29ycmVjdEhvcnNlQmF0dGVyeVN0YXBsZQ==" bw --check --nointeraction --response unlock`

and this is slightly more usable (but still not ideal).

1. With valid session key:
`{"success":true,"data":{"noColor":false,"object":"message","title":"Vault is unlocked!","message":null}}` <-- STDOUT
Exit code is 0

2. With invalid session key:
`Session key is invalid.` <-- STDOUT
`mac failed` <-- STDERR
`{"success":false,"message":"Vault is locked."}` <-- STDERR
Exit code is 1

3. With user logged out:
(No output to STDOUT)
`{"success":false,"message":"Vault is locked."}` <-- STDERR
Exit code is 1

My third option (and would actually the best if I could get consistent output because I don't have to check the status of the vault beforehand) would be:

`BW_SESSION="Q29ycmVjdEhvcnNlQmF0dGVyeVN0YXBsZQ==" bw --nointeraction --response get username b84272cf-c397-446e-9896-a9d4dad9a38d`

1. With valid session key:
`{"success":true,"data":{"object":"string","data":"user@example.com"}}` <-- STDOUT
(No output to STDERR)
Exit code is 0

2. With invalid session key:
`Session key is invalid.` <-- STDOUT
`mac failed` <-- STDERR
`{"success":false,"message":"Vault is locked."}` <-- STDERR
Exit code is 1

3. With user logged out:
(No output to STDOUT)
`{"success":false,"message":"You are not logged in."}` <-- STDERR
Exit code is 1

In no cases can I predictably get machine-readable output from either STDOUT or STDERR.
Would it be possible to get machine-parseable output (JSON) to stdout in *all* cases when using `--response` (and send any human-readable errors to stderr if required)?

**Comment by MGibson1** [comment]
Should not have been auto-closed
