### ISSUE TITLE
`--apiKey` is not accepted by CLI (requires `--apikey`)

### ISSUE THREAD

**Issue by luckman212** [bitwarden/cli#189]
The documentation says to pass the `--apiKey` parameter to login by API:
https://bitwarden.com/help/article/cli/#logging-in

but, this is not accepted:
```
$ bw login --apiKey

  error: unknown option `--apiKey'
```

It does seem to accept a lowercase `k`
```
$ bw login --apikey
? client_id: user.XXXXX
? client_secret: XXXXX
You are logged in!
```

`bw` installed via NPM, ver 1.13.3 on macOS 11.0.1

**Comment by kspearrin** [comment]
@fschillingeriv @addisonbeck `--apikey` is the correct parameter

**Comment by fschillingeriv** [comment]
Good spot, [fixed all mentions](https://github.com/bitwarden/help/pull/303)
