### ISSUE TITLE
Access Secure Notes without parsing json

### ISSUE THREAD

**Issue by AaronNBrock** [bitwarden/cli#196]
Is it possible to get the value without parsing JSON? I was hoping for something like:

```
bw get notes 'gitlab access token'
```

Just like you can easily fetch the password value..

I've re-read the docs, and searched the internet without anything helpful.

(I'm blatantly ripping off @ironhouzi's comment on #81 as a new issue to bring attention to this)

**Comment by clayadams5226** [comment]
Hey @AaronNBrock ,

We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
