### ISSUE TITLE
2FA method and code parameter lead to false login message

### ISSUE THREAD

**Issue by blacs30** [bitwarden/cli#20]
bitwarden-cli version 1.1.0 on macOS 10.13.6

The account has 2FA enabled via Authenticator App. I can login successfull via cli this way:

`bw login <user> <pw> --code <code>`

If I do `bw login <user> <pw> --method 0 [ or 5] --code <random-code>` where <random-code> is *NOT* a valid code from the Authenticator app but just arbitrary numbers -  the result is
```
You are not logged in.`

...
$ bw list items --session cJ1xGm7zjtw+xHdIEOiJ//wRgMT4y/XXXXXXXXXXXX8OeH/C4NOOAym9qN9e/TdCwBpYKaCacA8mSEDX3LeQ==
```

This message is falsely returned I believe as I cannot use the session id, bitwarden tells me that I am not logged in - which is then again correct.

So security wise that's not an issue but it's still not the correct behavior I would assume.

**Comment by kspearrin** [comment]
Fixed in next version. Thanks.
