### ISSUE TITLE
Generate passphrase ignores other parameters

### ISSUE THREAD

**Issue by drtomasso** [bitwarden/cli#201]
Hi

I'm having an issue with the password generator when using the passphrase option. It always comes in lower case and no numbers, even when specified.

Command:
`bw generate -puln`

Expectation: Passphrase with uppercase, lowercase and number
Actual result: Passphrase with lowercase only

TIA

**Comment by kspearrin** [comment]
This is expected. Only `length`, `words`, and `separator` apply to passphrases. Perhaps we need to update our docs a bit to be more clear.

**Comment by drtomasso** [comment]
Why is the cli generator different than all the other apps? Desktop and mobile apps can toggle capitalize and include digit.

If it's per design cli doesn't include this, then this is of course not an issue, but a feature request instead.

**Comment by kspearrin** [comment]
Those options were added to other clients at a later date and the CLI was missed. It is a feature gap.
