### ISSUE TITLE
Error The model state is invalid when using apikey

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/cli#205]
Hi guys,

I am unable to log in to my account via CLI + API key. I got "The model state is invalid" error message.
Tried on Windows Powershell & Linux platform.  However, using username & password is fine. I am also able to login to a new account I created for testing using API key.

Will provide account details via support ticket.

**Comment by cscharf** [comment]
see also, https://community.bitwarden.com/t/sso-issues-with-desktop-app-and-cli/15604

**Comment by clayadams5226** [comment]
@sso-bitwarden did Chad's comment help? Can we close this out?

**Comment by clayadams5226** [comment]
It appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
