### ISSUE TITLE
Bitwarden Cli for Windows is triggering a Trojan Malware alert

### ISSUE THREAD

**Issue by haneef95** [bitwarden/cli#210]
Hi,

Any fixes in the pipeline to avoid this?

![image](https://user-images.githubusercontent.com/298208/103685027-68f38800-4f84-11eb-9e7b-cfec9856d212.png)

Thanks,

**Comment by haneef95** [comment]
Just tried VirusTotal as well:
![image](https://user-images.githubusercontent.com/298208/103685644-7bba8c80-4f85-11eb-91f9-6ff2e8238539.png)
Source: https://www.virustotal.com/gui/file/1ae451e3be06f9c9f281d89352dcc544d69d26653915308c8f507f240fdfab20/relations


![image](https://user-images.githubusercontent.com/298208/103685787-b3293900-4f85-11eb-861d-1a75d25c72c8.png)
Source: https://www.virustotal.com/gui/file/c5f57ed9043511b0b9053cba041f00ae77356585430c53320079b66f64c4bca5/detection

**Comment by kspearrin** [comment]
Looks like a false positive on the ShadowHammer rule. See https://github.com/advanced-threat-research/Yara-Rules/commit/ec7d07b57eae1a67ac9ba3fc3f63bc19faa4b084
