### ISSUE TITLE
bw login: having the password in clear text exposes it in shell history. Security concern?

### ISSUE THREAD

**Issue by ggrelet** [bitwarden/cli#213]
Hello and sorry if that's not the right place to post this.

Upon login with your password:
```
bw login my_email@me.com my_password123
```

The command is stored in you shell history:
```
history | grep password123
 9210  dd/mm/yyyy  bw login my_email@me.com my_password123
```

This seems like a **security concern**. One could imagine the CLI should ask for it by prompting an hidden password user input just after launching `bw login`. What's your organisation opinion on this?

Thanks for your time. I much appreciate this product and I'm beginning to look into its CLI.

**Comment by fabh2o** [comment]
Try `bw login`

**Comment by ggrelet** [comment]
That's correct, thanks!
