### ISSUE TITLE
Unable to use CLI in Docker container

### ISSUE THREAD

**Issue by MaxRink** [bitwarden/cli#214]
We have an docker-based build enviroment and wanted to use bitwarden as a poor-mans-vault.
So ive tried running the bitwarden CLI inside a docker container.
The problem is, that bw login always aborts with exitcode 1 and returns
```
[object Object]
```
So the CLI is not useable in Docker.
Ive tried multiple base containers (python:latest, ubuntu:latest) and different Docker Versions (19.x and 20.x) to no avail.
Kernel in use is 5.4, but ive also tried 4.4 (with 3.10 i get the same behaviour on the host that runs docker, not just inside the container)
So i would assume that some library uses smth that is not aviable in a docker cgroup but is outside of an container.

**Comment by MGibson1** [comment]
I'd like a little more info as to how you're install bw on your container.

I'm able to get a working CLI by using a node container (https://hub.docker.com/_/node/) and installing bw with `npm install -g @bitawarde/cli`.

**Comment by MaxRink** [comment]
i've cpoied the prebuilt binary into an ubuntu container, as i didnt want all node dependencies

**Comment by MGibson1** [comment]
That's an interesting idea. I still can't reproduce though.

Using both node:latest and ubuntu:latest I was able to copy the snap image installed on one machine and run it. The donor machine is an arch-based vm if it helps. I tested far enough to run `bw login`, export the session id, and `bw list items`. No issues.

If you're not copying over the snap, it's not actually a binary you're getting. Most distributions are just node scripts, which doesn't explain the generic issue you're getting, but might help explain the general problem.

**Comment by LoveIsGrief** [comment]
It might be useful for the Bitwarden org to provide an official Docker image for the CLI client.

**Comment by dwbit** [comment]
Hey MaxRink, we haven't heard from you in a while, so we'll be closing this issue. 

LoveisGrief, thanks for the suggestion and for creating the feature request on the Bitwarden Community Forums to continue the discussion.

**Comment by LoveIsGrief** [comment]
I forgot to mention this issue in the [community](https://community.bitwarden.com/t/include-docker-image-with-cli-client/40400). Thanks for reminding me
