### ISSUE TITLE
Dependency Vunerability: Update Papaparse

### ISSUE THREAD

**Issue by DeveloperKhan** [bitwarden/cli#215]
Our project uses bitwarden/cli as a devDependency for our secrets script. Dependabot has recognized a security vunerability with papaparse. Unfortunately this can only be resolved if bitwarden/cli updates its dependency.

![A191A131-25B6-4906-BC3C-72FCAA5F1FD7](https://user-images.githubusercontent.com/26877561/104848013-0cac3480-58b1-11eb-8ce9-c7b798ad48a6.jpeg)

**Comment by x11x** [comment]
npm audit is also now showing vulnerabilities in node-fetch and node-forge packages.

**Comment by djsmith85** [comment]
Hi @DeveloperKhan and @x11x thank you for your reports. I just checked and we upgraded `papaparse` to `5.3.0`, `node-fetch` to `2.6.1` and `node-forge` to `0.10.0`. As the reported issues has been resolved I'm closing this now.
