### ISSUE TITLE
Error while creating an entry

### ISSUE THREAD

**Issue by Yamakaky** [bitwarden/cli#22]
I'm trying to create multiple login/password entries from the cli. If I try to create:

`{   "organizationId": null,   "folderId": "xxxxxxxxx-xxxx-xxxx-xxxxxx",   "type": 1,   "name": "name",   "notes": "Some notes about this item.",   "favorite": false,   "fields": [],   "login": null,   "secureNote": null,   "card": null,   "identity": null,   "note": "" }`

I get

```
(node:24307) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'uris' of null
    at Function.toView (/snapshot/cli/build/bw.js:40339:17)
    at Function.toView (/snapshot/cli/build/bw.js:30719:84)
    at CreateCommand.<anonymous> (/snapshot/cli/build/bw.js:82471:124)
    at Generator.next (<anonymous>)
    at __awaiter (/snapshot/cli/build/bw.js:82421:71)
    at new Promise (<anonymous>)
    at __awaiter (/snapshot/cli/build/bw.js:82417:12)
    at CreateCommand.createCipher (/snapshot/cli/build/bw.js:82470:16)
    at CreateCommand.<anonymous> (/snapshot/cli/build/bw.js:82459:39)
    at Generator.next (<anonymous>)
(node:24307) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24307) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What did I miss? [The doc](https://help.bitwarden.com/article/cli/#create) doesn't show how to create a login/password item.

**Comment by kspearrin** [comment]
What is the command you are running?

**Comment by Yamakaky** [comment]
I'm sorry :

`echo <json> | bw encode | bw create item`

**Comment by kspearrin** [comment]
If you are creating an item of type login (1), then you need to provide the `item.login` template in the `login` field. Right now it is just null, which is invalid.

**Comment by kspearrin** [comment]
See here for more info on using templates: https://help.bitwarden.com/article/cli/#templates

**Comment by Yamakaky** [comment]
Right, sorry, I didn't understand it that way. Maybe clarify the doc, with a password entry creation example?

**Comment by yngvark** [comment]
I also encountered this, as a total newbie to bitwarden. I think this doc needs to be updated:
https://help.bitwarden.com/article/cli/#create

which just states

```
bw create (item|attachment|folder|org-collection) [encodedJson] [options]
```

It doesn't give examples, which I think is the most important. Second, the syntax doesn't state that item has "sub types" (it's hidden in the appendix), nor does it link to https://help.bitwarden.com/article/cli/#templates

**Comment by yngvark** [comment]
See #51 for a working example. Would be nice if there was doc for how to actually create an item without resorting to trial and error.

**Comment by louwers** [comment]
It's annoying that the default template is not a valid JSON for the type it is supposed to be a template for.
