### ISSUE TITLE
Releasing a new version to be able to use encrypted exports

### ISSUE THREAD

**Issue by serhatcetinkaya** [bitwarden/cli#225]
Hello, as of I am writing this the latest version of bitwarden/cli is `1.13.3` and it was released on 2 December 2020. I quickly skimmed through the commit history and I found [this one](https://github.com/bitwarden/cli/commit/30b7b93fab73cd0bcdbec1b59274c5dbb248a5a9) has what is needed to be able to use encrypted_json exports on 8 December 2020 and obviously not included in `1.13.3` release. 

So what we need is a new release that includes the commit mentioned above

**Comment by cscharf** [comment]
Hi @serhatcetinkaya , Our releases do take some time to rollout all of the various clients, etc. the CLI is still on our radar and I had inquired about that earlier this morning as well with the team. We'll get it out soon. Thanks!

**Comment by MGibson1** [comment]
Chad made sure a release was cut yesterday which included encrypted export. Enjoy!
