### ISSUE TITLE
bw sync should have option to avoid prompting for password

### ISSUE THREAD

**Issue by macrozone** [bitwarden/cli#231]
`bw sync` tries to unlock the vault when the BW_SESSION is wrong. 

this breaks usage in other shells. It should have a non-interactive mode that throws an error if vault is locked

**Comment by MGibson1** [comment]
@macrozone there is a global `--nointeraction` setting that short circuits asking for a password and throws to stderr instead.

Please feel free to reopen if this isn't what you're looking for.

**Comment by macrozone** [comment]
@MGibson1 thanks, i'll check that out! I did not see that in the help, so that's why i raised the issue.

**Comment by MGibson1** [comment]
No worries, it's understandable.

The option is a program-wide one, and Commander subcommands' help menus do not display program-wide options. I'll think through if/how to solve that.

Please let us know of any other ideas you have!

**Comment by macrozone** [comment]
> No worries, it's understandable.
> 
> The option is a program-wide one, and Commander subcommands' help menus do not display program-wide options. I'll think through if/how to solve that.
> 
> Please let us know of any other ideas you have!

it works perfectly, thank you!
