### ISSUE TITLE
Feature Request: Feature flag to disable cli search wildcard wrapper.

### ISSUE THREAD

**Issue by McLain114** [bitwarden/cli#238]
I have some scripts that rely on specific, often similarly named vault items (often the name is in a portion of other vault item names). The ability to disable the wildcard wrapper would make pulling back a specific vault item by unique name much easier. I know that there are vault item ids that are unique. But, those are unique to a user and as this particular script is consumed by many users, it would be easier if the names could just be searched explicitly as given. I ended up coming up with a workaround for it. But, it isn't ideal and I'd much rather just be able to pass a flag to be able to search for a specific name.

I essentially would like to run something like:
bw get password --no-wildcard-wrapper uniquename

and be met with the unique entry instead of the following:
More than one result was found. Try getting a specific object by `id` instead. The following objects were found:

**Comment by McLain114** [comment]
I'll leave this open for now. At least until there is confirmation that what I am asking has been seen.

I did find the proper channels and added the request here:
https://community.bitwarden.com/t/feature-flag-to-disable-cli-search-wildcard-wrapper/19333

**Comment by MGibson1** [comment]
@McLain114 sorry for the ghosting! We've been working hard on a release we hope everyone will love.

Thanks for making a community post requesting this feature, that is indeed the proper channel. I'm going to close this and respond in that forum. Talk to you soon!
