### ISSUE TITLE
can you update deprecated packages?

### ISSUE THREAD

**Issue by crucifyer** [bitwarden/cli#239]
> warning @bitwarden/cli > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @bitwarden/cli > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @bitwarden/cli > jsdom > request > har-validator@5.1.5: this library is no longer supported

thank you.

**Comment by cscharf** [comment]
This is on our backlog, however we're not tracking these here. Package updates need to be made to 5+ repos in-sync and are often a rabbit hole that requires regression testing which impacts our team's capacity. Thank you for the report, however this will now be closed.
