### ISSUE TITLE
iTerm /others slab integration

### ISSUE THREAD

**Issue by g4challenge** [bitwarden/cli#24]
as in the unofficial client a slab command for iterm would be awesome.

@birlorg already did some work, but somehow it did not make it onto this client.

https://fossil.birl.ca/bitwarden-cli/home

Would it be possible to take the rust/python implementation into this cli? Or do i just need to create a coprocess command?

Thanks a lot

**Comment by birlorg** [comment]
@g4challenge I don't really understand.

My python version should *just work* with iTerm2 as a coprocess, the docs show what to type in to get it setup.

For the official client, which this repo is about, I haven't tried it, but you can probably make a wrapper around it to work very easily.

something like

``` bw list | choose | bw get```

Would probably get you pretty far. (where choose is either the chooser I use/recommend on macOS or something like fzf)

Alternatively send in a patch to make it work more directly might be appreciated, but I can't speak for bitwarden.

**Comment by heywoodlh** [comment]
@g4challenge I wrote a simple shell script for this here: [https://github.com/heywoodlh/bw-scripts](https://github.com/heywoodlh/bw-scripts)

Like @birlorg recommends in [Bitwarden CLI](https://github.com/birlorg/bitwarden-cli) I also recommend using [Choose](https://github.com/sdegutis/choose) on MacOS to be your fuzzy selector for SLAB functionality. If you're using `choose` you can steal the following snippet from my script for your own setup:

```
SELECTION="$(bw list items --search 'sudolikeaboss://' --session "$BW_SESSION" | jq -r '.[].name' | choose)"

bw get password "$SELECTION" --session "$BW_SESSION" | pbcopy
```


My two cents on SLAB being built in to `bw`: I'm not really sure it's a good idea to add SLAB functionality into `bw`. I think the design of `bw` as minimal as it is is pretty smart. That way others can build their own processes around it. I.E. you can write a shell script to do SLAB for you using `bw` to find and retrieve the passwords.

**Comment by creatorKoo** [comment]
I make some working stuff. and working good.

Please check out. 

https://github.com/creatorKoo/bitwarden-iterm-helper
