### ISSUE TITLE
bw {list, get} outputs "mac required." before expected result

### ISSUE THREAD

**Issue by basilpapadimas** [bitwarden/cli#246]
I am on Arch Linux and Fedora with bitwarden-cli 1.14.0 and nodejs v15.11.0 and v14.15.4, respectively. I installed bw with npm but tried the native executable as well. Trying to fetch a password with _bw list_ or _bw get_ currently behaves like this on both systems, with the same account:
```
bw get password github      

? Master password: [hidden]
mac required.
mac required.
mac required.
mac required.
mac required.
mac required.
mac required.
mac required.
hunter2
```
which isn't the expected output! I am not sure what is causing this, and I couldn't find any similar bugs on Google. I also
don't get why it says mac since I've never logged in to Bitwarden on a mac?! Please tell me if you need any more details on my setup. I could try reproducing this on other platforms or accounts, as well.

**Comment by cscharf** [comment]
Odd, the `mac` is for decryption, not the device type; part of AES and SAH256 comparisons. Are you able to connect and work within your vault via another client like the web vault or desktop app? You're hitting [this line of code](https://github.com/bitwarden/jslib/blob/master/src/services/crypto.service.ts#L606), which we would have to do a little digging to figure out _why_, someone more familiar than me may be able to figure this one out quicker.

**Comment by basilpapadimas** [comment]
I can actually log in to the web vault and the mobile apps just fine. Since it looks like this has to do with encryption, I changed my master password and rotated the encryption key, but nothing changed. I suspect there must be some corrupted data on my vault (which contains only passwords and a credit card), because when I tried to reproduce this on a brand new account on the same system everything behaved normally. I can export the vault and search for said corruption but I don't know what to look for.

**Comment by cscharf** [comment]
I'm not sure you would be able to find the issue by exporting... although perhaps you can export your vault, do a sanity check on the data (to ensure it's complete), then delete all of the items in your vault (and empty trash) and re-import, that should remove any vault item that somehow got corrupted (never seen that happen but there's a first for everything). Just be sure if you do this, if you export using encrypted JSON format, you can not re-import that if you rotate your keys again or use a different/new account (even with the same master password).

**Comment by basilpapadimas** [comment]
I just imported the whole vault into the new account without making any changes to the .json file and everything seems to work normally. This thing is still pretty weird but since I will probably simply write off the old account, I can close this issue. Except if you think it's worthwhile to find what's behind this quirky behavior, then we can look into this further and find what's wrong with the old account.

**Comment by cscharf** [comment]
Thanks @basilpapadimas , I'm glad the export/import worked, although odd, there have been a few changes over the years which required data transition and something may have gotten corrupted along that journey... I'm not sure how old your account is but it would be difficult to really troubleshoot it further as we wouldn't have access to your vault and it would probably require a lot of back-and-forth, etc.

For now, please close this issue but feel free to re-open it (or if anyone else in the community has the same problem they can re-open it as well) and we can try to track it down further. Thanks again!

**Comment by basilpapadimas** [comment]
Thank you!

**Comment by a7g4** [comment]
Not sure if I should create a new issue but I'm seeing the issue now. Is there anything I can do to gather more data?

![2022-05-17_13-03](https://user-images.githubusercontent.com/38473816/169101474-41f68031-1172-4ac5-86fa-51f3ef508c34.png)
