### ISSUE TITLE
fzf helper

### ISSUE THREAD

**Issue by autoferrit** [bitwarden/cli#26]
I just wanted to post, i use `fzf` regularly. and i managed to make a helper to easily search for a login and copy the password to the clipboard using `xclip`. To use this you need:

`fzf`
`jq`
`xclip`

and in your bash or zsh profile, add this function

```bash
bwcopy() {
  if hash bw 2>/dev/null; then
    bw get item "$(bw list items | jq '.[] | "\(.name) | username: \(.login.username) | id: \(.id)" ' | fzf-tmux | awk '{print $(NF -0)}' | sed 's/\"//g')" | jq '.login.password' | sed 's/\"//g' | xclip -sel clip
  fi
}
```

Then source the file to activate, then just run `bwcopy` and you will see a list of all of your logins in the format:
```
name: [name] | username: [username] | id: [id]
```
start typing the name of the login, and when you select one with `[enter]` it will copy the password field to your clipboard. I thought this helper might be able to be added to the docs somewhere on https://help.bitwarden.com/article/cli/#get

I hope others find it useful

**Comment by g4challenge** [comment]
Thanks a lot, that was about what I was looking for.

Just a question, your snippet works to create the `bwcopy` function and i can select the login, but unfortunately the clipboard stays unchanged. When only using the snippet without `xclip` i see the pwd in plain text in stdout.

Using MacOS 10.13 iTerm 3.2.0 and zsh.

could you share your steps you used?

**Comment by g4challenge** [comment]
Found out a possible way to do this on OSX securely as `xclip` does not work. 

Using secure-pbcopy (https://github.com/alyssais/secure-pbcopy) it is possible to conceal the input and use it.

```
bwcopy() {
  if hash bw 2>/dev/null; then
    bw get item "$(bw list items | jq '.[] | "\(.name) | username: \(.login.username) | id: \(.id)" ' | fzf-tmux | awk '{print $(NF -0)}' | sed 's/\"//g')" | jq '.login.password' | sed 's/\"//g' | pbcopy-secure
  fi
}
```

Hope this helps for anyone reading through it.

**Comment by autoferrit** [comment]
i think on osx, xclip has to be installed. when I do this, it never shows my password anywhere. it also works on linux and does not show my password.

**Comment by philipsd6** [comment]
Here's my version for the fish shell. It uses the fzf `--with-nth` parameter to hide the UUID from the display. Using the primary selection with xclip is what works best for me, but you can switch that to clip if desired. YMMV.

```fish
function bwcopy
    if command -sq bw and command -sq fzf-tmux and command -sq xclip
        bw get item (
            bw list items \
            | jq -r '.[] | [.name, .login.username // "", .id] | @tsv' \
            | column -t -s \t \
            | fzf-tmux --with-nth 1..-2 --preview-window down:2 \
                       --preview 'bw get item (echo {} | awk \'{print $NF}\') | jq -r \'.login.uris | .[] | .uri // empty \'' \
            | awk '{print $NF}'
        ) | jq -r '.login.password' | xclip -selection primary
    end
end
```

**Comment by aaronkjones** [comment]
For OSX this worked for me:
`brew install xquartz`
`brew install jq xclip fzf`

echo pbcopy function to `~/.oh-my-zsh/custom/bw.zsh`
`source ~/.zshrc`

Reboot (to get xquartz working)

**Comment by aaronkjones** [comment]
Also, I called this function bwget instead of bwcopy.
For bwcopy I have this in the event I know the exact item name:

```
bwcopy() {
        bw get password "$1" | pbcopy
}
```

Thanks a lot for this.

**Comment by luciano-fiandesio** [comment]
The `fish` version of the `bwcopy` script posted by @philipsd6 works for me only if I add the `--sync` flag to `fzf`

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. I love the tips & tricks here, but I'm closing this so that it doesn't clutter up bug reports.

The [User-to-User support](https://community.bitwarden.com/c/support/6) section of the [Bitwarden Community Forums](https://community.bitwarden.com) might be a better place for discussing this, or you can submit a [feature request](https://community.bitwarden.com/c/feature-requests) if you think there's something we could improve in the CLI client itself. Thanks all!
