### ISSUE TITLE
`bw send create` does not honor --fullObject flag

### ISSUE THREAD

**Issue by luckman212** [bitwarden/cli#268]
**related to https://github.com/bitwarden/cli/issues/265**

```shell
#!/bin/bash
encoded=$(bw send template send.text | jq '
  .name="foo" |
  .maxAccessCount=3 |
  .text.text="bar baz"' |
  bw encode)
bw send create --fullObject "$encoded"
```

should output in JSON format, but only prints the "standard" output:

```
Send created! It can be accessed at:
https://send.bitwarden.com/#-xxxxxxxxxxxxxxxxxxxx
```

**Comment by MGibson1** [comment]
This is an oversight.

(Commander)[tj/commander], the library we're using for our CLI command framework allows for `git`-like commands which have different options. There are a few we've designated as top-level (raw, session, a few others) that work anywhere, but `fullObject` isn't one of those. I wrote it only for the `bw send` command, and failed to extend to the `bw send create` command.

I'll mark this as an enhancement and good first issue. If anyone would like some direction, let me know.

**Comment by hantatsang** [comment]
@MGibson1 Do you have examples in code where options are shared between parent and sub-commands? I've tried [`program.passThroughOptions`](https://github.com/tj/commander.js/blob/master/examples/pass-through-options.js) but have no luck.

**Comment by MGibson1** [comment]
@hantatsang, not really. The way we're doing it now is only at the very tippy top level in [`program.ts`](https://github.com/bitwarden/cli/blob/master/src/program.ts#L37-L74).

For this feature, I wouldn't want to set an environment variable and process that down the line. I'd rather repeat the option code (seen in [sendProgram.ts](https://github.com/bitwarden/cli/blob/master/src/send.program.ts)).

It looks like `passThroughOptions` is not to make all subcommands recognize options, but to allow for reordering of them.

**Comment by hantatsang** [comment]
`--fullObject` option has already been repeated to `SendProgram#createCommand` 

https://github.com/bitwarden/cli/blob/3ca615327052d8701cc14c463779c232bb4ef29b/src/send.program.ts#L163-L173

But when running `bw send create --fullObject`, `createCommand` still doesn't recognize `fullObject` in the options. I'm not sure what's wrong here with Commander.

**Comment by MGibson1** [comment]
You're right! I should have checked code first.

It looks like what's happening is that commander is assigning that `--fullObject` option to the `bw send` part of the command and it's not left over for `bw send create` to handle. That's unfortunate.

I hope there's a better solution, but what I know off the top of my head is to either:
1. Rename the option in `bw send create` (pretty terrible solution)
2. Use the third parameter of the `.action` method to pull out the `command.parent`'s options and merge with the ones given to the action.

I don't much like either solution. I don't know if Commander has this, but it'd be nice to at least be able to use some kind of AllOptions object that just has all the flags set at every level of the application.

Thanks for helping dig into this.
