### ISSUE TITLE
export cannot receive a master password with multiple leading dashes

### ISSUE THREAD

**Issue by cmaahs** [bitwarden/cli#271]
## Describe the Bug

If your password contains at least two leading `-` characters the command will fail.

```bash
% bw export "--mypassword" --format json
error: unknown option '--mypassword'
```

## Steps To Reproduce

See above

## Expected Result

Command should run as expected.

## Actual Result

error: unknown option '--mypassword'

## Environment

- Operating system: MacOS
- Shell: zsh
- Build Version (run `bw --version`): 1.15.1

**Comment by sso-bitwarden** [comment]
try this.
bw export -- "--mypassword" --format json

**Comment by cmaahs** [comment]
Accepted, however there is an ordering problem:

The other parameters MUST appear before the `-- "--mypassword"`

`bw export --format json --output /tmp/out.json -- "--mypassword"`
