### ISSUE TITLE
bw list items: organizationid and folderid are not both used to filter the results

### ISSUE THREAD

**Issue by cmaahs** [bitwarden/cli#272]
## Describe the Bug

If one provides --organizationid AND --folderid parameters to the `bw list items` command, only the --organizationid is used to filter the returned items.

## Steps To Reproduce

1. Identify a organizationId: `bw list items | jq '.[].organizationId' | sort --unique`
2. Identify a folderId: `bw list items | jq '.[].folderId' | sort --unique`
3. List both folderId and organizationId: `bw list items | jq '(.[] | [.folderId, .organizationId])'`
4. Run variations of the `bw list items` command

- `bw list items --organizationid notnull --folderid notnull | jq '(.[] | [.folderId, .organizationId])'`
- `bw list items --organizationid <valid_org_id> --folderid <valid_folder_id> | jq '(.[] | [.folderId, .organizationId])'`
- `bw list items --folderid <valid_folder_id> --organizationid <valid_org_id> | jq '(.[] | [.folderId, .organizationId])'`

## Expected Result

When both parameters are provided, the output should contain items that match both parameters.

## Actual Result

When organizationid and folderid are provided, ALL items for the ORG are returned, not just the items that match the folderId.

## Environment

- Operating system: MacOS
- Shell: zsh
- Build Version (run `bw --version`): 1.15.1

**Comment by sso-bitwarden** [comment]
Hi,

Are you aware that there is no folder in organization items? only collections

**Comment by cmaahs** [comment]
That isn't exactly true.  If I create an item, sort it into a Folder in my personal list, and then share it out to an Organization/Collection, the resulting object JSON will contain the correct `folderId`, `organizationId`, and also an array of `collectionIds`.  

As the original owner who assigned it to a Folder, that item will show up for me both in the Organization/Collections AND also in the correct Folder that I originally assigned it to.

It also appears to be fairly smart, in the fact that when I list an item that is from another's personal list, and shared out to the Organization/Collection, even though they have assigned it a Folder in their personal list, the server sends me the object with the `folderId` set to null, which makes sense since I wouldn't actually have that particular `folderId` defined.  

Since the underlying data does allow an object to contain both fields with values set, it makes sense to use both in the filtering logic in the `list items` command.
