### ISSUE TITLE
Ambiguous error message for incorrect master password or two-step code

### ISSUE THREAD

**Issue by seanfarley** [bitwarden/cli#28]
If a user inputs an incorrect password, the output is `The model state is invalid` ... which is the same error message for an incorrect two-step verification code. It'd be preferable if the error codes had some uniqueness to them (e.g. "incorrect master password entered") so that we could parse that easier in scripts.

**Comment by kspearrin** [comment]
```
$ bw login
? Email address: hello@bitwarden.com
? Master password: [hidden]
Username or password is incorrect. Try again.
```

What command/options did you use?

**Comment by kspearrin** [comment]
Self hosting with the official Bitwarden server or something else?

**Comment by seanfarley** [comment]
Unofficial :-( I'm guessing since it works for you that enough to put the blame on the rust image I'm using.

**Comment by kspearrin** [comment]
Sounds like their server isn't sending proper error messages back. I'd contact them about it.

**Comment by seanfarley** [comment]
Thanks for your help in debugging; much appreciated :-)
