### ISSUE TITLE
Unique exit codes

### ISSUE THREAD

**Issue by seanfarley** [bitwarden/cli#29]
Similar to #28, this issue is about using unique exit codes for the different types of errors. For example, instead of exiting with `1` for every error, not logged in could return `1`, but locked vaults could return `2`. I would hope this could be extended to all states: "more than one result found", etc. so that we could refer to a documented mapping of exit codes and errors.

Thanks!

**Comment by tukusejssirs** [comment]
Was this issues fixed? I think that Bitwarden CLI should definitely use unique exit codes per error.

**Comment by dancorne** [comment]
Please don't close! It'd be useful for scripting to know if `bw` is returning an error due to not being logged in, unlocked, or not finding an item.

**Comment by dwbit** [comment]
Hey everyone, since this is a request/discussion, we'll be moving it over to the Bitwarden Community Forums and closing the issue. There isn't currently a post in the [Feature Requests](https://community.bitwarden.com/c/feature-requests) category for this functionality, so you are welcome to create one.

**Comment by tukusejssirs** [comment]
@dwbit, why don’t you simply move the open issues to BCF instead of simply closing the issues? Closing the issues won’t solve them.

**Comment by dwbit** [comment]
Thanks for the feedback @tukusejssirs. Since this request is from 2018, the best way to move forward is to fascinate further discussion, and the best place for that is the forums. Anyone is free to create a post to kick-off the chat.

**Comment by tukusejssirs** [comment]
Well, I’ve been notified (by @bitwarden-bot) of about 4 other issues that they are labelled ~stale. What about moving these issues directly to the forum and the moderators sort the issues out there?

**Comment by dwbit** [comment]
Thanks again for the feedback. We're responding to and reviewing all stale label comments. As the moderator for the forums, I'll share any existing discussions/feature request links if available. Feature Requests are tied to user accounts on the forums, and anyone in this thread is welcome to continue the conversation there by creating one.
