### ISSUE TITLE
CLI --apikey doesn't bypass SSO policy requirement for non-admin, non-owner

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/cli#297]
## Describe the Bug

Need a way to log in using CLI as non-admin & non-owner. 
I was told that --apikey was supposed to bypass this but that wasn't the case.

## Steps To Reproduce

1. Enable SSO & SSO authentication policy
2. Login via CLI using --apikey

## Expected Result

able to login

## Actual Result

error 
{"response":null,"statusCode":500}

**Comment by eliykat** [comment]
Fixed: https://github.com/bitwarden/server/pull/1308
Thanks @MGibson1 for jumping on this and @winklevos for the original report.
