### ISSUE TITLE
Bitwarden CLI Beta Test

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/cli#3]
The Bitwarden CLI is now available as a public beta test.

![CLI](https://imgur.com/MPPu112.png "CLI")

## Download/Install

**NPM**

```
npm install -g @bitwarden/cli
```

**Native Executables**

During this beta test, you can download the latest executables for Windows, macOS, and Linux from our CI build artifacts, here: https://ci.appveyor.com/project/bitwarden/cli/build/135/artifacts

## Documentation

See help center article with detailed documentation here: https://help.bitwarden.com/article/cli/

## Feedback

Provide any bug reports, questions, and/or feedback in this issue. Please do not open a new issue.

Also, please provide feedback on the help documentation at https://help.bitwarden.com/article/cli/

**Comment by edouardmenayde** [comment]
Hi ! So cool the cli is here ! It's really sweet and the documentation is great. However I have one little problem : when I use backspace while typing the password the action has no effect (visually or functionally).

**Comment by kspearrin** [comment]
@edouardmenayde This is fixed in next version (1.0)

**Comment by kspearrin** [comment]
This beta is now over. See blog post here for official release announcement: https://blog.bitwarden.com/bitwarden-command-line-tool-now-available-e6184407b719
