### ISSUE TITLE
cannot authenticate from windows (native bw.exe, or linux @bitwarden/cli

### ISSUE THREAD

**Issue by aram535** [bitwarden/cli#302]
## Describe the Bug

Cannot authenticate to the bw service.

## Steps To Reproduce
Linux:
1. $ sudo npm install -g @bitwarden/cli 
2. $ bw login 
<enter any email> 
<enter any password>

Windows:
1. Download bw.exe from github, version: 1.16.0
2. Extract binary 
3. Run c:\bw.exe login
<enter any email> 
<enter any password>

## Expected Result

Authentication and auth code

## Actual Result

Red text reading (dns ec2 instance name changes if you try from different systems at different times but the message remains constant)
[Linux]
request to https://o7anokdow4.execute-api.us-east-1.amazonaws.com/api/accounts/prelogin failed, reason: getaddrinfo ENOTFOUND o7anokdow4.execute-api.us-east-1.amazonaws.com

[Windows]
request to https://y9npmms3vb.execute-api.us-east-1.amazonaws.com/prod/api/accounts/prelogin failed, reason: getaddrinfo ENOTFOUND y9npmms3vb.execute-api.us-east-1.amazonaws.com y9npmms3vb.execute-api.us-east-1.amazonaws.com:443

## Screenshots or Videos

available upon request.

## Environment

- Operating systems: [Windows 10 Home, CentOS 8.3 x64]
- Shell: CMD, bash 
- Build Version (run `bw --version`): 1.16.0
- npm version for linux: 7.12.1
- I am using PiHole as my DNS server (bind 9 as the forwarder).  I have disabled PiHole and the results are the same.  I verified with https://mxtoolbox.com/dnscheck.aspx that the host names do not resolve).

**Comment by MGibson1** [comment]
This looks like an issue with your CLI config settings going to your self hosted instance.

Here's our help page on that kind of configuration: https://bitwarden.com/help/article/change-client-environment/#cli

**Comment by aram535** [comment]
Odd, I just installed the tools and npm version.  I'll check it, thx.
