### ISSUE TITLE
Trouble with syntax for bw send create using send.file template

### ISSUE THREAD

**Issue by luckman212** [bitwarden/cli#303]
Sorry if this is the wrong place for this.

```shell
$ bw --version
1.16.0
```

I'm trying to use `send.file` template in a script to create File Sends, but I'm failing somewhere. Here's the basic format I'm using:

#### bwtest.sh:
```shell
#!/usr/bin/env bash

function _bwsend() {
  [ -e "$1" ] || return
  bw send template send.file |
  jq --arg f "$1" '.name="foo" | .text="bar" | .notes="mynote" | .file.fileName=$f' |
  bw encode |
  bw send create --fullObject
}

_bwsend "$1"
```

```
$ bwtest.sh "some_file.zip"
Must specify text content to Send either with the --text option or in the encoded json
```

I've tried many different permutations of the command arguments but can't seem to find the magic incantation. Any tips?

**Comment by cscharf** [comment]
@MGibson1 , you put together some pretty great examples of this style of automation via CLI, any thoughts?

**Comment by MGibson1** [comment]
The trouble is an issue with the send templates. It appears we are not setting the send type to `File` for `bw send template send.file`. 

For now, you can just add `.type = 1` to your `jq` string:
```
  jq --arg f "$1" '.name="foo" | .text="bar" | .notes="mynote" | .file.fileName=$f | .type=1' |
```

**Comment by luckman212** [comment]
Thanks @MGibson1 — setting `.type = 1` works.

There are still other problems though.  See #305.
