### ISSUE TITLE
Import / Edit of organistation folder

### ISSUE THREAD

**Issue by mortenbirkelund** [bitwarden/cli#31]
I have a task that I am unsure if can be done in Bitwarden CLI, and how. 

I have an organisation folder. (Backends). I would like to replace the password of all logins in this folder by using the CLI. 

I am considering 2 approaches. 
1. Delete the current folder, Create a new organisation folder and import alle the logins using the import functionality. 
2. Get a list of all entries within the organisation folder, and edit the password one by one. 

What is the best/easiest solution?
Does CLI support editing organisation folders/logins?

**Comment by kspearrin** [comment]
I am a little confused by "organization folders". Are you referring to collections?

**Comment by mortenbirkelund** [comment]
Yes that would be the correct term. Collections.

**Comment by kspearrin** [comment]
The CLI currently does not offer the ability to manage collections directly. You cannot delete them from the CLI. Your only option would be to edit each item in the collection one by one.

**Comment by mortenbirkelund** [comment]
When you say one by one, do you mean using the web interface?

Could it be of interest to add this functionality to the cli? It is a must for our organization to be able of editing the password of the 200+ sites automatically and have them shared to all within the organization.

**Comment by kspearrin** [comment]
No, I mean one by one using the CLI. You can certainly edit items as is defined in the documentation.

**Comment by mortenbirkelund** [comment]
Okay. When I execute this command, then I get a list of ALL my entries, and not only the entries that exist in the collection. Is the issue with my command, or is this a bug?

bw list items --collectionid {THE_ID_OF_THE_SPECIFIC_COLLECTION]

**Comment by kspearrin** [comment]
It was a bug. Should be fixed next version.

**Comment by mortenbirkelund** [comment]
Do you know when the next version will be released? The possibility to only list logins from within a collection is crucial for our use of bitwarden. I would like to move our company to bitwarden but it is not possible until my automated password replacement script is working perfectly 😊

**Comment by kspearrin** [comment]
Hopefully later this week.

**Comment by mortenbirkelund** [comment]
Thank you for your quick respons

**Comment by kspearrin** [comment]
Now available in 1.4.0

**Comment by mortenbirkelund** [comment]
Awesome. Thank you. Will test it soon

tir. 16. okt. 2018 18.36 skrev Kyle Spearrin <notifications@github.com>:

**Comment by mortenbirkelund** [comment]
Awesome. Thank you for notifying me. I will test soon

**Comment by mortenbirkelund** [comment]
@kspearrin Works like a charm. Thanks
