### ISSUE TITLE
Import directly to organization vault

### ISSUE THREAD

**Issue by alancivita** [bitwarden/cli#317]
Hi, is there a way to import items directly into the organization vault? the cli offers only a way to export from org but not import.
As a workaround i was thinking of import items into the admin vault and the use the cli to change the oranizationID, but it's not very elegant

Thanks

**Comment by MGibson1** [comment]
Howdy!

Only the web vault is able to import data. However, the good news is that there is a separate import page for an organization! You just need to navigate to the organization's vault. We actually have a help page detailing the process (https://bitwarden.com/help/article/import-to-org/).

I'm going to close this. If you need help getting to your organizations web vault, feel free to re-open the ticket and ask away 😉

**Comment by alancivita** [comment]
Hi and thanks for the quick reply.
I've altrady tried it but the problem is that when i import the item into the org vult through the web interface it doesn't import the folders (which occurs if import it into the personal vault) and so i need to find a way to rebuild all the structure .. it would be nice to be able to convert the folders into collections or something similar

**Comment by MGibson1** [comment]
From where are you importing? The importer _is_ supposed to convert folders into collections for Organization imports.

Unfortunately the workaround you propose wouldn't create that folder structure for anyone but you. Folders are specific to user vaults, they don't organize items within an organization for everyone else.

**Comment by alancivita** [comment]
I was importing the items through org vault web interface. 
I will give it another  go tomorrow
Thanks for your help

**Comment by MGibson1** [comment]
Sorry I mean what type of information -- Who made the export?

**Comment by alancivita** [comment]
ah ok, so i've exported all the items from my personal vault in bitwarden, which is organised by folders, and imported it into the org vault.

**Comment by timwsuqld** [comment]
Given that the CLI export already allows imports into personal vaults, and exports from personal vaults and organizations, it would be really good if the CLI could be updated to also allow importing to an organisation vault.

**Comment by MGibson1** [comment]
@timwsuqld, Import is seen as an onboarding item, rather than something that needs the ability to automate or be accessible from all clients. For now we're not planning on expanding import beyond just the web client.

Happy to hear use cases, though

@alancivita It sounds like the import ended up working out fine. Is that correct?

**Comment by alancivita** [comment]
@MGibson1  Hi matt, sort of. We ended up writing a program in python to sort the collection "issue" we had. 
Now we have a usable system
Thanks

**Comment by timwsuqld** [comment]
@MGibson1 we are looking to replace an existing system and bitwarden is on the table for consideration. As our organisation is already a heavy user of the other system, we'll need to do a lot of importing. It is much easier for us to script something like this, exporting from the other product each individual vault/collection and importing them into the new correct one. Having to import via the web interface just makes this more cumbersome, and importing into the admin's vault and then moving isn't a good option for us either.

I understand not wanting to implement something like import in all clients, but the CLI seems like the perfect place for it as the CLI is often used in automation. Especially as the CLI can already import into the admin's vault, importing into the organisation vault isn't a big step past the existing functionality.

**Comment by alancivita** [comment]
@timwsuqld Hi, ifyou are interested i can share the script in php we've used to create the json file, populated with collections, ready to be imported into bitwarden.
Alan

**Comment by MGibson1** [comment]
@timwsuqld that does sound like a good use case. I'll look into what it would take to add organization imports today.

**Comment by timwsuqld** [comment]
@MGibson1 Thanks heaps for that. That's awesome

**Comment by MGibson1** [comment]
Unfortunately, it won't make the release we're working on right now, but It'll be in the next.
