### ISSUE TITLE
Provide an URI match command or option

### ISSUE THREAD

**Issue by ewjoachim** [bitwarden/cli#32]
I'm implementing a bitwarden [keyring](https://pypi.org/project/keyring/) backend using bitwarden-cli. I'll be provided with a URL and a username, and will need to return the appropriate password. I'd like to be able to use the full system of URI matching that's in place in other clients (especially in browser extensions) but that may prove complicated if I have to reimplement the whole logic on my side. I'm guessing that bitwarden cli has this functionnality in its code already, but if I'm not mistaken, it's not exposed. Is there a way this could be exposed somehow ? Maybe a `bw list --match-uri=<match>` ?

**Comment by kspearrin** [comment]
Added `bw list items --url https://google.com` for next version

**Comment by ewjoachim** [comment]
Wow that was fast ! Thank you a lot ! Any idea when that might land in a release ? Thanks again, this is going to remove quite some code from [bitwarden-keyring](
https://pypi.org/project/bitwarden-keyring/)

**Comment by kspearrin** [comment]
Not sure. Maybe this coming week.

**Comment by kspearrin** [comment]
Now available in 1.4.0
