### ISSUE TITLE
`--passwordenv` doesn't work for for unlock.

### ISSUE THREAD

**Issue by anonymous1184** [bitwarden/cli#335]
## Describe the Bug

This is not a bug, is kind of an omission:

`--passwordenv` doesn't work for for unlock (most likely `--passwordfile` is also not supported).

## Steps To Reproduce

In a terminal (using Windows as example):

```cmd
set BW_RAW=true
set BW_PRETTY=true
set BW_PASSWORD=<Redacted>
bw logout >nul 2>&1
bw login <Redacted> --passwordenv BW_PASSWORD --method 0 --code 123456
set BW_SESSION=<Session key>
bw status
bw lock
bw unlock --passwordenv BW_PASSWORD
```

## Expected Result

Base64 string (session key).

## Actual Result

StdErr:

```cmd
error: unknown option '--passwordenv'
```

## Screenshots or Videos

`--passwordenv` doesn't work, password does:

![20210627064616](https://user-images.githubusercontent.com/53758552/123543577-dbb01580-d714-11eb-906c-916c3b6dd609.png)

## Environment

- Operating system: All
- Shell: Any
- Build Version: 1.16.1

## Additional Context

Login works as expected, I didn't check `--passwordfile` and haven't check the source code for this, but most likely won't work either.

**Comment by eliykat** [comment]
I agree this seems like an omission. @MGibson1 do you have any objection to us adding these options for `unlock` as well?

If not, I think it would be a good one for a community member to work on, if anyone wants to pitch in.

**Comment by MGibson1** [comment]
This is an oversight.

Back in January, I noticed that `--passwordenv` and `--passwordfile` didn't work with login. I didn't think to add those options to `bw unlock`.

The implementation should be pretty identical to the [`login.command`](https://github.com/bitwarden/jslib/pull/253/files#diff-5cf0198cf17f18aef484c36d722e1955d182165081b5325510f377c7a6d7b7c1R115-R118)

**Comment by Philser** [comment]
If nobody is working on it yet then I'd like to give it a try.
