### ISSUE TITLE
MacOS ZIP for v.17.0 empty

### ISSUE THREAD

**Issue by MarcelBochtler** [bitwarden/cli#341]
## Describe the Bug

The ZIP for the [1.17.0 version for MacOS](https://github.com/bitwarden/cli/releases/tag/v1.17.0) is empty.
It's only 22 bytes big and cannot be unzipped.

**Comment by cscharf** [comment]
Thanks, we're working through a last-minute regression issue that was found in CLI and it was too late to cancel the build/deployment. Tagging the DevOps folks here just in case we need to look at the build pipeline/actions.

**Comment by MarcelBochtler** [comment]
@cscharf was the issue fixed? I see a that the `bw-macos-1.17.0.zip` is now a valid zip file and contains `bw`.

**Comment by cscharf** [comment]
Hi @MarcelBochtler , yes, this was a build-pipeline issue which was resolved. We will be pushing a new CLI v1.17.1 here either later today or tomorrow as well.

**Comment by luckman212** [comment]
@cscharf When is the new build being pushed? I use the CLI a lot... hoping the release comes before we start this long weekend

**Comment by cscharf** [comment]
Officially we've found a couple of issues that we want to address before we do the release, but if you're in a sticky spot and need the current 1.17.0 bits, they're packaged in this build here: https://github.com/bitwarden/cli/actions/runs/990303717

**Comment by luckman212** [comment]
Thanks, confirmed that the updated build does work for me. So, good workaround for now. Good luck on the other fixes!
