### ISSUE TITLE
Incorrect metadata

### ISSUE THREAD

**Issue by anonymous1184** [bitwarden/cli#349]
## Describe the Bug

Windows binary has incorrect metadata.

## Steps To Reproduce

Display `bw.exe` properties

## Expected Result

Bitwarden CLI metadata

## Actual Result

NodeJS metadata

## Screenshots or Videos

![20210708195917](https://user-images.githubusercontent.com/53758552/125008030-3c015a00-e027-11eb-96c4-e2906e574c74.png)

## Environment

- Operating system: Windows
- Shell: Not applicable
- Build Version: 1.17.1

## Additional Context

Got a node error that I couldn't replicate anymore when I tried to sync. Guess after the JSON updated I cannot replicate.

**Comment by joseph-flinn** [comment]
This issue has been fixed and will appear in the next cli release.
