### ISSUE TITLE
```bw generate``` doesn't give a monkey about options

### ISSUE THREAD

**Issue by Bibelo** [bitwarden/cli#354]
## Describe the Bug

bw generate does not seems to take options into account

## Steps To Reproduce

1) First, the doc reads
> By default, the generate command will generate a 14-character password with uppercase characters, lowercase characters, and numbers. This is the equivalent of passing:

Giving the impression that by default, bw cli generates password with only u, l and n.

Not the case:

```
bw generate
zUE$BKBFF!o66W
```

**Question : I want to generate a password with only u, l, n. Please how do I do that?**

2) Then I wonder what's the point of the `-s` option. I don't seem to see any difference.

With:
```
bw generate -s
oHwJ*rh2Pe7txc
bw generate -s
PmnF!PUV^yH7*j
```

Without:
```
bw generate
etU!3rgvzpU$4W
bw generate
dnq6aG8Ho^f6!C
```

3) I never managed to generate a passphrase.
(That woud solve my problem of having a password without special characters.)

Using the example given in the doc :

```
bw generate --passphrase --words 3 --separator -
DBLJ@8oAdNd9iE
```

I know there's probably an explanation, but it's not clear to me. In that case, it should be made clear in the documentation.

For example, instead of :
> By default, the generate command will generate a 14-character password with uppercase characters, lowercase characters, and numbers

> By default, the generate command will generate a 14-character password with **at least** uppercase characters, lowercase characters, and numbers. **It is not possible to generate passwords with only uppercase characters, lowercase characters, and numbers.**

## Environment

- Operating system: Ubuntu 18.04.1 LTS
- Shell: bash
- Build Version : 1.17.1

Edit: typos

**Comment by SergeantConfused** [comment]
Hi @Bibelo,

I have tested this on Ubuntu 20.04.2 LTS and Bitwarden CLI 1.17.1, and the options are working properly. I tested your syntax 'bw generate --passphrase --words 3 --separator -' and it resulted in a 3 word passphrase.

Please uninstall it, reboot your machine, install it anew (I'm using snap), and let me know if that helps.

Thank you in advance,

**Comment by Bibelo** [comment]
Thanks @SergeantConfused I tried what you said

Rebooted the server, install with snap (previous installation was wget from link given in the doc)

Result is exactly the same.

I assume bw does not have dependancies, so I'd be curious to know if others have the problem with 18.04.
