### ISSUE TITLE
[FEATURE] Create organization item via CLI

### ISSUE THREAD

**Issue by geraldaistleitner** [bitwarden/cli#36]
I tried to create an item with an organization id set but all I get is "The model state is invalid.", without setting the organizationId it works.

Environment:
Self-Hosted on docker
Admin user role
Logged in with two factor authentication via bw login and setting the BW_SESSION environment variable

`bw get template item  | jq '.login = {"uris":null,"username":"jdoe","password":"myp@ssword123","totp":null}' | jq '.name = "test"' | jq '.organizationId = "XXX-XXX-XXX-XXX"' | bw encode | bw create item`

My questions now is, is it supported to create a shared item via CLI or do I have some problem with my setup?

**Comment by kspearrin** [comment]
This should be properly supported in the next version of the CLI. You will have to `create` the item first, then use the new `share` command to transfer it to the organization and collections.

**Comment by geraldaistleitner** [comment]
Great news, thanks @kspearrin for the fast answer.
