### ISSUE TITLE
bw get password [uri] only matches first URI entry

### ISSUE THREAD

**Issue by mattydebie** [bitwarden/cli#37]
I noticed that when trying to get the password from a URI, it only works if you try to find the first of the defined URI's. Take for example following entry:
```json
{
  "object": "item",
[..]
  "login": {
    "password": "thispassword",
    "uris": [
      {
        "match": null,
        "uri": "firsturl.eu"
      },
      {
        "match": null,
        "uri": "secondurl.io"
      }
    ],
[..]
}
```
If you'd try `bw get password firsturl.eu` you would get `thispassword` as response.
When executing `bw get password secondurl.io` you get `Not found`.

**Comment by kspearrin** [comment]
Yes, the basic search functions will only use the first URI. If you want to use a more robust search, try using the `--url` option on `bw list items`.

```
bw list items --url secondurl.io
```

**Comment by mattydebie** [comment]
Oh okay, so this is intended behavior?

**Comment by kspearrin** [comment]
Yes.

**Comment by mattydebie** [comment]
Alright, then I will close this issue. Thanks for the feedback!
