### ISSUE TITLE
bw get attachment still asking for Master password even with session id

### ISSUE THREAD

**Issue by sedwo** [bitwarden/cli#378]
I need to script a CI/CD step where a key file is pulled from BitWarden to build the app.

My testing with:  `bw get attachment <attachment_id> --itemid <uuid> -session <session id>`

continues to always ask for a `Master password`.

_fyi_ :  I also use `export NODE_TLS_REJECT_UNAUTHORIZED=0` if that matters.

Is there a way to overcome this `Master password` prompt?

**Comment by sso-bitwarden** [comment]
Hi @sedwo 

You may want to check whether the session ID is still valid. I couldn't reproduce the issue.

[root@bitwarden ~]# bw get attachment InvoiceNAME.pdf --itemid "249d74e8-dcf7-451b-be6c-MASKED" --session P2B0cczmGACmlObKWHsH958Ga14+QeN3/akYqEMY+0hBjM2rGsMtCsZf3jMASKED
Saved /root/InvoiceNAME.pdf

[root@bitwarden ~]# export NODE_TLS_REJECT_UNAUTHORIZED=0
[root@bitwarden ~]# bw get attachment InvoiceNAME.pdf --itemid "249d74e8-dcf7-451b-be6c-MASKED" --session P2B0cczmGACmlObKWHsH958Ga14+QeN3/akYqEMY+0hBjM2rGMASKED
Saved /root/InvoiceNAME.pdf

**Comment by sedwo** [comment]
I tested my status:
```
[~]: bw status --pretty
{
  "serverUrl": "<internal on-prem server>",
  "lastSync": "2021-09-27T23:08:09.639Z",
  "userEmail": "-----@----.com",
  "userId": "...",
  "status": "locked"
}

[~]: bw unlock         
? Master password: [hidden]
Your vault is now unlocked!

To unlock your vault, set your session key to the `BW_SESSION` environment variable. ex:
$ export BW_SESSION="..."

[~]: bw status --pretty
{
  "serverUrl": "<internal on-prem server>",
  "lastSync": "2021-09-27T23:08:09.639Z",
  "userEmail": "-----@----.com",
  "userId": "...",
  "status": "locked"
}

¯\_(ツ)_/¯
```

but.... I just unlocked you...

**Comment by Alexander-Shukaev** [comment]
I have this problem now.  Exporting `BW_SESSION` does not prevent `export` command to ask for password, it does so regardless.

**Comment by Alexander-Shukaev** [comment]
See suggestion in [Why does CLI export ask for password?](https://community.bitwarden.com/t/why-does-cli-export-ask-for-password/18155/4) as well:
> Does `export` support `BW_SESSION` environment variable or not?  If it does not, this needs to be implemented ASAP.  Supplying passwords on command-line invocation is a major security risk.  Environment variables are also a security risk, but better than nothing.  Bitwarden team should also strongly consider to implement standard input descriptor password/secret entry (e.g. via pipe) for CLI application as it is done in any sane secret-related software in the UNIX world as this delivers most security.

**Comment by Alexander-Shukaev** [comment]
And just to finalize this request in general, I believe all the CLI commands should have consistent interface including authentication/decryption credential expectations.  Currently, some read environment variables, some have command-line explicit options, and some expect positional arguments.  Both options and positional arguments should be banned/deprecated in favor of better security.  Only those options and positional arguments can remain, which indirectly reference a secret, e.g. to be read from environment variable with a specified name.  In addition to environment variables, standard input descriptor reading for all kinds of secrets is the most secure way, which should also be possible if done via pipe to achieve automation.
