### ISSUE TITLE
Duo support in CLI?

### ISSUE THREAD

**Issue by ventz** [bitwarden/cli#39]
Hi,

Any reason for Duo not being supported in the CLI client?

It seems the jslib auth.service already supports Duo:
https://github.com/bitwarden/jslib/blob/f16fc58d707b9ed55355e62440fb95185f972090/src/services/auth.service.ts

And there are valid methods for Duo in the CLI:
```
// CONCATENATED MODULE: ./jslib/src/enums/twoFactorProviderType.ts
var TwoFactorProviderType;
(function (TwoFactorProviderType) {
    TwoFactorProviderType[TwoFactorProviderType["Authenticator"] = 0] = "Authenticator";
    TwoFactorProviderType[TwoFactorProviderType["Email"] = 1] = "Email";
    TwoFactorProviderType[TwoFactorProviderType["Duo"] = 2] = "Duo";
    TwoFactorProviderType[TwoFactorProviderType["Yubikey"] = 3] = "Yubikey";
    TwoFactorProviderType[TwoFactorProviderType["U2f"] = 4] = "U2f";
    TwoFactorProviderType[TwoFactorProviderType["Remember"] = 5] = "Remember";
    TwoFactorProviderType[TwoFactorProviderType["OrganizationDuo"] = 6] = "OrganizationDuo";
})(TwoFactorProviderType || (TwoFactorProviderType = {}));
```

Or is it just no time/not a priority?

If it will help, there's an NPM Duo API module here:
https://www.npmjs.com/package/@duosecurity/duo_api

With docs for the auth here:
https://duo.com/docs/authapi#/auth

Thanks!

**Comment by kspearrin** [comment]
It's not supported today because the Duo flow for a non-GUI interface is much different than what we use for all the other apps that do have a GUI (Duo Web SDK).

For now, a backup 2FA method (Auth app, email, or Yubikey) is required.

**Comment by ventz** [comment]
@kspearrin I don't know the internals of BW (specifically around the way you hook into your auth js library), but I can write a working Duo end-to-end example that you can just plug in. Would this be helpful? I am assuming you have a lot going with everything else - I definitely want to help if I can with this (we would use it heavily)

**Comment by kspearrin** [comment]
I'm waiting to hear back from Duo about some issues regarding support this via Duo Auth API from the CLI.

**Comment by ventz** [comment]
@kspearrin Thanks! Let me know if I can help somehow. If you want, check out LastPass-CLI too -- they have Duo auth implemented from the CLI (https://github.com/lastpass/lastpass-cli)

**Comment by ktreese** [comment]
Hello @kspearrin @ventz It would seem this is still outstanding.  Is there still not an available means of using the cli for Duo users?  Thanks!

**Comment by kspearrin** [comment]
@ktreese It is still TODO. We finally got approved by Duo for support on their HTTP API, so we can look at this now again whenever I get some time.

**Comment by ventz** [comment]
@kspearrin That's great!!

**Comment by kspearrin** [comment]
I looked into this again, and it appears that Duo still has not properly enabled the Bitwarden application to use the Auth API. I have sent them another email requesting an update.

**Comment by atbtechgit** [comment]
Thanks, Kyle. We were trying to implement this into one of our apps and this is stopping us at the moment.

**Comment by kspearrin** [comment]
@atbtechgit The workaround would be to enable another supported 2FA option on the account you are trying to use with the CLI.

**Comment by atbtechgit** [comment]
Would I be able to do that? Duo is setup at the org wide level.

**Comment by kspearrin** [comment]
Yes, you can still use another 2fa method. You just can't not use 2FA if the org has setup Duo, since that option will always be provided.

**Comment by atbtechgit** [comment]
Thanks, Kyle. That does seem to work. Is there any way to auto-authenticate using Authy or something? Basically, I need to pass my auth token into my app when I am trying to login. I'm not sure if this has been done before.
