### ISSUE TITLE
Warns installing on node 16 with npm 8

### ISSUE THREAD

**Issue by agriffis** [bitwarden/cli#404]
## Describe the Bug

It installs and works on node 16 but with a warning.

## Steps To Reproduce

Install node 16 and npm 8 then try the command above. On Fedora, I installed with this:

```
sudo dnf module install nodejs:16/default
```

then run the command

```
npm i -g @bitwarden/cli
```

## Expected Result

Installed without warning

## Actual Result

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@bitwarden/cli@1.19.1',
npm WARN EBADENGINE   required: { node: '~14', npm: '~7' },
npm WARN EBADENGINE   current: { node: 'v16.11.1', npm: '8.1.2' }
npm WARN EBADENGINE }
```

**Comment by djsmith85** [comment]
Closing this, as it is only a warning due to using an unsupported version of (node/npm). Further comment on the linked PR.
