### ISSUE TITLE
Logging in with --apikey doesn't respect two step settings

### ISSUE THREAD

**Issue by detunized** [bitwarden/cli#409]
## Describe the Bug

I have enabled the OTP in the account settings and when I log in with the username/password pair I get prompted for the `Two-step login code`. With the `--apikey` switch I'm allowed to log in with the client_id/client_secret pair alone.

## Steps To Reproduce

1. Log in the with `--apikey` switch:

```bash
export BW_CLIENTID=user...
export BW_CLIENTSECRET=N9M1...
bw login --apikey
```

2. Observer the output:

```
You are logged in!
```

## Expected Result

A 2FA code is requested during the login process.

## Actual Result

No 2FA is requested.

## Environment

- Operating system: macOS Monterey
- Shell: zsh
- Build Version (run `bw --version`): 1.19.1

## Additional Context

Is this the expected behavior or a bug? I could not find a clear statement in the documentation that 2FA is ignored during the `--apikey` login process.

**Comment by eliykat** [comment]
This is intended, `--apikey` is for automated workflows where you don't want manual interaction to complete the 2FA step.

@fschillingeriv could you review the documentation and update if required?

**Comment by detunized** [comment]
@eliykat thank you for the clarifications
