### ISSUE TITLE
CLI doesn't support deleting collections

### ISSUE THREAD

**Issue by Swonkie** [bitwarden/cli#42]
According to the [documentation](https://help.bitwarden.com/article/cli/#delete) it should be possible to delete collections.

However the local help text of the delete command lists only these deletable objects:

    Objects:
      item
      attachment
      folder

I wasn't able to delete collections.

**Comment by kspearrin** [comment]
The docs were incorrect. I have updated them. Deleting collections from the CLI is not yet supported.
