### ISSUE TITLE
`bw lock` causes logout

### ISSUE THREAD

**Issue by hkariti** [bitwarden/cli#439]
## Describe the Bug
Starting with cli version 1.20,  trying to lock the vault results in this message and a logout:
```
You cannot lock your vault because you are using Key Connector. To protect your vault, you have been logged out.
```

## Steps To Reproduce

Login via a password and 2fa:
```
$ bw login $EMAIL
? Master password: [hidden]
? Two-step login code: 

You are logged in!

To unlock your vault, set your session key to the `BW_SESSION` environment variable. ex:
$ export BW_SESSION="..."
> $env:BW_SESSION=".."

You can also pass the session key to any command with the `--session` option. ex:
$ bw list items --session ...
```
Then try to lock:
```
$ bw lock
You cannot lock your vault because you are using Key Connector. To protect your vault, you have been logged out.
$ bw login --check
You are not logged in.
```

## Expected Result
Since I don't use Key Connect, I expect to get the same result as in version 1.19:
```Your vault is locked.```

## Actual Result
```
You cannot lock your vault because you are using Key Connector. To protect your vault, you have been logged out.
```

## Environment

- Operating system: macOS Monterey
- Shell: zsh
- Build Version (run `bw --version`): 1.20.0

**Comment by dh024** [comment]
Same behaviour is reported on the Bitwarden community forums here:
https://community.bitwarden.com/t/bitwarden-cli-you-cannot-lock-your-vault-because-you-are-using-key-connector-to-protect-your-vault-you-have-been-logged-out/36885/5

**Comment by eliykat** [comment]
Thanks for reporting this - I read through the community forums thread and your report here and I confirm this is not the expected behaviour. I'll look into it.

**Comment by samba2** [comment]
@eliykat just want to add on that I am facing the same issue. I posted my experience in the same forum thread. Tnx for looking into it !

**Comment by RayneShall** [comment]
Is the fix for this available on 1.20.0 already? I can see it's been merged to master, but there's no update available from CLI. Is this implemented if re-downloading the native installers/snap?

**Comment by eliykat** [comment]
@RayneShall this fix will be in the next release, which is currently scheduled for ~10 February. Alternatively, you could build the last release from source using the `v1.20.0 tag` and then cherry-pick the commit over, if you need the fix before then and feel comfortable with that process.

**Comment by RayneShall** [comment]
@eliykat Awesome, thanks! No need to build beforehand, just wanted to have a better idea on when to expect
