### ISSUE TITLE
Export of organization entries is not possible

### ISSUE THREAD

**Issue by 0xERR0R** [bitwarden/cli#44]
I can share passwords to organization, in this case the password entry will be transfered to the organization vault. In web UI i can perform csv export for user and organization, but i can only export user entries via cli. Is it possible to export/import organization entries? I could not found any options on the help page.

**Comment by kspearrin** [comment]
There are no organization management options available via the CLI at this time. You will need to use the web vault.

**Comment by TwoTwenty** [comment]
I would like to see this feature. My organization just purchased a multi user license yesterday and we are self hosting due to data sovereignty laws in BC/Canada. it would be incredibly useful to script/tailor the backup of the data.

**Comment by kxcooper** [comment]
I want this too please.
Better still, an encrypted backup of both user and organisation entries.
Not sure how to securely pass password to CLI but give me the option to back up my vault and I'll find a way.

**Comment by cmaahs** [comment]
This is now in the CLI and can be closed.

```plaintext
Usage: bw export [options] [password]

Export vault data to a CSV or JSON file.

Options:
  --output <output>                  Output directory or filename.
  --format <format>                  Export file format.
  --organizationid <organizationid>  Organization id for an organization.
  -h, --help                         display help for command
```

**Comment by eliykat** [comment]
Cheers @cmaahs
