### ISSUE TITLE
login error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by BorjaLL** [bitwarden/cli#472]
running the command `bw login` and inputting email and password results in 
`request to https://api.bitwarden.com/accounts/prelogin failed, reason: unable to get local issuer certificate`

if I run `set NODE_TLS_REJECT_UNAUTHORIZED=0` I am able to log in

**Comment by MGibson1** [comment]
Are you behind a network proxy that may be handling your SSL validation for you? Maybe a temporary DNS issue while we updated?

**Comment by BorjaLL** [comment]
I'm probably behind a proxy and heavy antivirus/firewall that I cant interact with

**Comment by MGibson1** [comment]
This appears to be a local network config problem. I suggest raising the issue with your Proxy admin as blocking TLS certificates.

**Comment by BorjaLL** [comment]
they wont change anything.
it would be helpful if we could have a mode that had the flag behaviour

**Comment by MGibson1** [comment]
In that case -- if you trust whoever is limiting your network -- I think the best thing to do would be to create an alias to set
```bash
alias bw = "NODE_TLS_REJECT_UNAUTHORIZED=0 bw"
```
should do on *nix. I'm less familiar with windows shells
