### ISSUE TITLE
bw generate fails on 1.21.0

### ISSUE THREAD

**Issue by dtrodrigues** [bitwarden/cli#476]
## Steps To Reproduce

Run
```
$ bw generate --length 10
```

## Expected Result

A generated password

## Actual Result

```
$ bw generate --length 10
/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:23842
            account.data.policies.decrypted = value;
                    ^

TypeError: Cannot read properties of undefined (reading 'data')
    at StateService.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:23842:21)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:23303:58)
```
## Screenshots or Videos
N/A

## Environment

- Operating system: macOS, Linux
- Shell: bash
- Build Version (run `bw --version`): 1.21.0

## Additional Context
This worked on 1.20.0.

Additional logs: https://github.com/Homebrew/homebrew-core/pull/94893

**Comment by eliykat** [comment]
I can reproduce this, although only when I'm not logged in. As a temporary workaround, you can log in (leave your vault unlocked if you want) and try again. I'll prioritise it for a fix.
