### ISSUE TITLE
bw list shows folders bw delete cannot remove

### ISSUE THREAD

**Issue by smsimeonov** [bitwarden/cli#48]
Running 1.7.0 on Powershell 5.1, installled via Chocolatey (if it matters)

Whenever I sync, after being logged on and fetching a Session Key by using **"bw unlock --raw"** and I try to do a check to see if an entry exists, **"bw list"** returns folders not existing anymore. I cannot delete them via **"bw delete"** either. Whenever I try, I get a _"Resource not found"_. No matter how many times I sync, they cannot be removed.
They don't show in the web interface as well.

**Comment by kspearrin** [comment]
Where are you seeing these folders? Just their ids within an item? Or using `bw list folders`? Any idea how to reproduce from my end?

**Comment by kspearrin** [comment]
When I run `bw list folders` I only see real folders from my vault, which I also see in the web vault.

When you list these folders, what is their name? Are they old folders you used to have or what?

**Comment by BigWax** [comment]
Yeah, they're old folders I created with the cli and then removed via the web interface since I was just starting out on using the cli itself.

**Comment by kspearrin** [comment]
What if you log out and back into the CLI?

**Comment by BigWax** [comment]
Doing that seems to have fixed it. 
Although ideally, I wouldn't have to do that since I'm trying to automate this through a script which executes remotely, so the less actions, the better.
Thanks for the quick responses by the way.
