### ISSUE TITLE
`bw get totp` claims I don't have premium

### ISSUE THREAD

**Issue by cerevka** [bitwarden/cli#482]
## Describe the Bug

When I use `bw get totp <id>` it tells me:
```
Premium status is required to use this feature.
```

even though I have active premium. I can get the TOTP via the web vault. My current version is `1.21.0`. 

When I do `snap revert bw` to version `1.20.0` it works again (but writes `mac failed.` twice to STDOUT).

## Steps To Reproduce

1. `bw login`
2. `bw unlock`
3. `bw get totp <id>`

## Expected Result

It should return the TOTP code.

## Actual Result

It writes error message `Premium status is required to use this feature.`

## Screenshots or Videos

none

## Environment

- Operating system: Ubuntu 20.04.3 LTS (from snap)
- Shell: zsh
- Build Version (run `bw --version`): 1.21.0

## Additional Context

I have `Premium account` hosted by bitwarden, no self-hosting. 
It works with 1.20.0 version.
`bw` is installed via snap.

**Comment by Hinton** [comment]
Hi @cerevka,

This issue should be fixed in https://github.com/bitwarden/cli/pull/477, but we haven't yet released a new version.

As a current work around, performing a sync should bring back premium.

**Comment by eliykat** [comment]
CLI v 1.21.1 has been released and includes the fix referred to above.

**Comment by cerevka** [comment]
Thank you, it works for me with the new version now.
