### ISSUE TITLE
keepass2xml import fails with "DOMParser is not defined"

### ISSUE THREAD

**Issue by edmellum** [bitwarden/cli#50]
When doing `bw import keepass2xml someexport.xml` it fails with "DOMParser is not defined". A brief glance of the [code](https://github.com/bitwarden/jslib/blob/cb7336c0e8ae1f0f74c76a4d6704555cc7440a3b/src/importers/baseImporter.ts#L69) leads me to think that the code is attempting to use `DOMParser` in Node.js, which is a browser API and isn't available in Node.

**Comment by kspearrin** [comment]
I guess we need to polyfill with something like https://www.npmjs.com/package/xmldom

**Comment by kspearrin** [comment]
Can you build and try master now to see if that resolves the issue? I added the xmldom polyfill.

**Comment by edmellum** [comment]
Awesome! That gets me past the previous error! 😄 Now I'm getting `doc.querySelector is not a function`. Maybe try adding a unit test that tries to import a basic KeePass 2 XML file?

**Comment by kspearrin** [comment]
Looks like xmldom doesnt support `querySelector()`. Need to figure out a way to support that in Node I guess.

**Comment by kspearrin** [comment]
Seems to work with jsdom lib. Test here: https://github.com/bitwarden/jslib/commit/93244b5c90b02ec7a333ffafe8b32a6026c1c7d3

Try pulling, installing, and building master again and let me know.

**Comment by kspearrin** [comment]
Nevermind, looks like something broke the build with jsdom. Will have to investigate more.

**Comment by kspearrin** [comment]
@edmellum Can you give it a try now? Had some issues with webpack and jsdom that should be resolved now. Could you also test it with the packaged binary as well? https://ci.appveyor.com/project/bitwarden/cli/build/artifacts

**Comment by edmellum** [comment]
The packaged binary works! :D Cloning the repo gives me this error though. "originalMethod.apply(...).finally is not a function"

**Comment by kspearrin** [comment]
Great. Did you run `npm i` after pulling?
