### ISSUE TITLE
`invalid password` on `1.22.0-1`, logs in on `1.21.1-1`

### ISSUE THREAD

**Issue by mizzunet** [bitwarden/cli#513]
## Describe the Bug

I cannot login on `1.22.0-1` but can login same account on `1.21.1-1`.

Server: `https://mizzunet.mycozy.cloud/bitwarden`

## Steps To Reproduce

You need https://cozy.io/en/ account to reproduce

1. Install `1.21.1-1`
2. Add server, `https://[username].mycozy.cloud/bitwarden`
3. Login, user is `me@[username].mycozy.cloud`
4. See that it logs in

Try same process on `1.22.0-1`

## Expected Result

Login succesfully

## Actual Result

Having this output,

`{"response":{"error":"invalid password"},"captchaRequired":false,"statusCode":401}`
## Environment

- Operating system: Artix
- Shell: fish
- Build Version (run `bw --version`): 1.21.1-1 and 1.22.0-1
- 
## Additional Context

Could it be the server's issue?

**Comment by kspearrin** [comment]
Hi. We don’t support cozy cloud severs. You should try contacting their support channels.

**Comment by mizzunet** [comment]
Aright
