### ISSUE TITLE
How do I add users to org-collections 

### ISSUE THREAD

**Issue by akashkroy** [bitwarden/cli#515]
## Describe the Bug
Not able to add users to org-collections 
I tried the following command but it doesn't work : 
```
echo '{"id":"49304e2d-c0e0-4bb5-a12b-c0bc578ad757", "object": "org-member"}' | bw encode | bw edit --organizationid 2a6ebb47-5d23-4a59-abd6-57b36b395e76 org-collection 2f99f6cb-e261-4d91-bcf0-c2534658bc74
```
## Error message 
`organizationid` option does not match request object.

## 
Checked if the user and collection belongs to the organization or not. 

## Environment

- Operating system: [Ubuntu]
- Shell: [bash]
- Build Version (: [1.22.0]

## 
Couldn't find anything in the docs on how to do this, so I came here. 

Thanks

**Comment by dwbit** [comment]
Hi @akashkroy, the best place to ask is the '[Ask the Bitwarden Community](https://community.bitwarden.com/c/support/6)' forum category. We only use Github to track bugs, so I'll close this issue now.
