### ISSUE TITLE
Trying to edit custom fields boolean from cli?

### ISSUE THREAD

**Issue by Syrou** [bitwarden/cli#52]
Am I missing something, or is it currently no support to edit a custom field? Lets say I have a custom boolean field, I'd like to swap between checked and unchecked form the command line, but there seems to be no support for this?

**Comment by kspearrin** [comment]
When you edit an item, the "fields" property allows you to set custom fields for that item.

**Comment by Syrou** [comment]
Not sure there does not seem to be such a thing from the cli:
bw edit (item|item-collections|folder) <id> [encodedJson]

basicly as far as I see it, the only way to change a custom field from the cli, is to replace the entire json for that object

**Comment by kspearrin** [comment]
Yes, that is correct.
