### ISSUE TITLE
CLI forbidding premium features on premium account

### ISSUE THREAD

**Issue by dewijones92** [bitwarden/cli#520]
My account is a premium account (dewijones92@gmail.com)
But the premium features are not working

## Steps To Reproduce

run this
`bw get attachment priv.key --itemid 8f8d4a81-d670-492b-89f7-ae6d0101a285`

## Expected Result

Should output the file content to standard output or should save the file

## Actual Result

Shows this error
`Premium status is required to use this feature.`

## Environment

- Operating system: Ubuntu
- Shell: bash
- Build Version (run `bw --version`): 1.22.0

**Comment by Hinton** [comment]
Hi @dewijones92,

Can you logout and login again and check if the error persists?

**Comment by tangowithfoxtrot** [comment]
Hey @dewijones92,

As mentioned by @Hinton, logging out and back in to the CLI should cause it to pick up your Premium status.

The issue here will be closed.
