### ISSUE TITLE
Open security vulnerabilities in node-forge dependency

### ISSUE THREAD

**Issue by andrew-chang-dewitt** [bitwarden/cli#521]
## Describe the Bug

See vulnerability reports:

1. https://github.com/advisories/GHSA-x4jg-mjrx-434g
2. https://github.com/advisories/GHSA-8fr3-hfg3-gpgp

## Steps To Reproduce

1. Install cli using `npm i @bitwarden/cli`
2. Review reported vulnerabilities using `npm audit`

## Expected Result

Should report no vulnerabilities.

## Actual Result

Instead reports 2 vulnerabilities in the version of `node-forge` that the cli depends on.

## Screenshots or Videos

```
andrew@book: ~/test
$ npm i -S @bitwarden/cli

added 214 packages, and audited 215 packages in 5s

17 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

andrew@book: ~/test
$ npm audit
# npm audit report

node-forge  <=1.2.1
Severity: high
Improper Verification of Cryptographic Signature in node-forge - https://github.com/advisories/GHSA-x4jg-mjrx-434g
Open Redirect in node-forge - https://github.com/advisories/GHSA-8fr3-hfg3-gpgp
No fix available
node_modules/node-forge
  @bitwarden/cli  *
  Depends on vulnerable versions of node-forge
  node_modules/@bitwarden/cli

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```

## Environment

- Operating system: Ubuntu 20.04 running in WSL2 on Windows 11 
- Shell: bash
- Build Version (run `bw --version`): 1.22.0

## Additional Context

Reviewing the reports from GitHub (linked above) shows both are fixed by updating `node-forge` version to 1.3.0 or greater. Current version is 0.10 per [`package-lock.json`](https://github.com/bitwarden/cli/blob/master/package-lock.json#L5308) & the dependency in [`package.json`](https://github.com/bitwarden/cli/blob/master/package-lock.json#L5308). I don't know what else would need to change as a result, but it appears that the fix will require updating `node-forge` to >= 1.3.0.

**Comment by Hinton** [comment]
Hi @andrew-chang-dewitt,

Thanks for letting us know. It seems I forgot one of the projects while I bumped node-forge for the other.
