### ISSUE TITLE
Feature request: option to check if vault is locked of unlocked

### ISSUE THREAD

**Issue by jalbstmeijer** [bitwarden/cli#54]
Hi,

Similar to https://github.com/bitwarden/cli/issues/27 it would be nice if the --check option would also output if the vault is locked or unlocked.

Maybe also related to https://github.com/bitwarden/cli/issues/29

This for scripting around the bw cli.

Gr, J

**Comment by DB-CL** [comment]
Hi, 

The PR has been merged but we are still waiting for a new version to come.

Does anyone knows when a new release will come out ?

Thanks !

**Comment by onedr0p** [comment]
This issue should be closed: `bw status` reports this info.

**Comment by tukusejssirs** [comment]
@onedr0p, thanks for the heads up!

Anyway, was `bw status` added recently? Because I can’t remember this command when I first started using `bw`.

**Comment by cscharf** [comment]
@tukusejssirs , was added ~ 9 months ago, https://github.com/bitwarden/cli/pull/145
