### ISSUE TITLE
TOTP not working for organization in self-hosted config

### ISSUE THREAD

**Issue by whitenoise2** [bitwarden/cli#55]
Bitwarden version 2.5.0, self-hosted on via Linux docker, with registered paid organizeation.
 
I can access TOTP codes that are shared with the organization via the web plugin, but cli keeps on claiming:
"Premium status is required to use this feature."

![flic-totp](https://user-images.githubusercontent.com/3268858/52919402-26f9c400-32d0-11e9-806d-5952dcba0b97.png)

![image](https://user-images.githubusercontent.com/3268858/52919410-36790d00-32d0-11e9-920c-ad0ccb1606b0.png)

**Comment by kspearrin** [comment]
I am having trouble reproducing the problem. What type of organization plan do you have?

**Comment by whitenoise2** [comment]
Thanks for the quick response. I am under the families plan.

![image](https://user-images.githubusercontent.com/3268858/52975589-16ab1d00-3394-11e9-9a33-5a303bfec715.png)

**Comment by kspearrin** [comment]
Thanks. I found the problem. Should be fixed in next version.
