### ISSUE TITLE
getting attachment by exact name

### ISSUE THREAD

**Issue by gingerlime** [bitwarden/cli#56]
I'm bumping into a minor issue when two attchments are similar, and I want to fetch them by exact name rather than id. 

A typical example: `id_rsa` and `id_rsa.pub` ... 

If I fetch `bw get attachment id_rsa.pub --itemid <...>` this works great.

But if I try to fetch `bw get attachment id_rsa --itemid <...>`, then I get

`More than one result was found. Try getting a specific object by `id` instead. The following objects were found:`

Yes, I can do some minor `jq` acrobatics and fetch the id, but I hope it can be simplified on the cli if possible (maybe a flag)? worth asking... :)

**Comment by jamesj2** [comment]
Here's what I came up with. It requires two hits to the bitwarden database but it does what I need it to do.
```
ID="BW ID"
FILE="output.txt"
bw get attachment $(bw get item $ID | jq ".attachments[] | select((.fileName == \"$FILE\")).id" -r) --output ./$FILE --itemid $ID
```
