### ISSUE TITLE
jsdom and webpack build problems

### ISSUE THREAD

**Issue by libertylocked** [bitwarden/cli#59]
In 1.7.0 when running webpack build, the `bw.js` bundle came with all the dependencies, which is excellent and can be used anywhere nodejs is installed. We can basically run `node /usr/lib/bitwarden-cli/bw.js` without having to use the binary built by `pkg` (since it's got a pretty fat nodejs runtime in it).

1.7.1 added `jsdom` and the webpack config doesn't build external `node_modules` into the bundle anymore, making it pretty difficult to use standalone.

I tried removing the externals from `webpack.conf.js` but it had some issue with canvas module not found.

I wonder if it's still possible to build a standalone javascript bundle?

**Comment by kspearrin** [comment]
I'm confused. Are you saying that local builds no longer work?

```
npm install
npm run sub:init
npm run build
cd build
node ./bw.js
```

**Comment by libertylocked** [comment]
Local build only works if node_modules are present at runtime.

Ideally the node_modules should be webpack compile time dependencies.

(You can also notice that bw.js is a lot smaller in 1.7.1 because a lot of
the deps aren't bundled)

You can reproduce the runtime dependency problem by:

- npm run build
- cp build/bw.js /tmp/bw.js (just copy the webpack output anywhere outside
the repo)
- cd /tmp
- node ./bw.js
- Get error about module not found

**Comment by kspearrin** [comment]
I see. Yes, `webpack-node-externals` was added to resolve the [canvas issues](https://github.com/Automattic/node-canvas/issues/1314) with using the new `jsdom` library to support the import command. See https://github.com/bitwarden/cli/issues/50

If you can figure out a way to work around those canvas errors, we can revert it. I couldn't.

If you have the node runtime already installed, can't you just install from npm?

```
npm i -g @bitwarden/cli
```
