### ISSUE TITLE
Keep vault perpetually unlocked?

### ISSUE THREAD

**Issue by octoxan** [bitwarden/cli#60]
I know this wouldn't be the best for security reasons, but for the application I'm going to be using it for it would be awesome if I could somehow keep the cli vault unlocked after unlocking it once?

Maybe on reboot it could lock or whatever, but ideally this would be a login once and you're in for good sort of thing.

I see this in the docs: "It is possible to persist your session key to your environment (for example, exporting it in .bashrc), however, we do not recommend doing this." although it seems I still need to unlock it on every new shell session?

Is this possible somehow, to just stay logged in?

**Comment by estheruary** [comment]
(Assuming that you're using bash) Does adding

```
export BW_SESSION="HugeReallyLongSessionKey=="
```

to your `~/.bashrc` not work?

**Comment by pascalandy** [comment]
I have the same requirement. 

At the moment I script heavily to to unveiled gpg secrets. The private key is always available on the server. So it acts like an "always unlock" vault.

I'll try :)

**Comment by cmbconcretefire** [comment]
Yeah I'd like to weigh in here > The fact that I use Bitwarden to store my passes and stuff.......it's a *HUGE* pain in the butt to have to keep typing in my vault password. ----- If you can't decide, FINE......let US decide. Make it an option to turn on or off please.

**Comment by estheruary** [comment]
Thoughts? https://github.com/bitwarden/cli/pull/179
