### ISSUE TITLE
`export` should export attachments too

### ISSUE THREAD

**Issue by nekorug** [bitwarden/cli#61]
Running v.1.7.0 on Arch Linux 5.0.3.

I want to use the `export` command to export my entire vault as a backup. In doing so i noticed that neither the csv or json exports contain any copy of or information about attached files. This makes my backup incomplete.

I know I can download attachments using `get attachment <filename> --itemid <itemid>`, and I could write a script to go through and save these, but ideally an export command should already export everything. Any custom solution I implement is not going to work with `import` either, which is not ideal.

Maybe the command could include any attachments as base64 encoded entries in the json/csv structure? Of course this would have to work in the reverse when you use `import` with the `bitwardencsv`/`bitwardenjson` entries.

**Comment by alxpy** [comment]
+1

**Comment by pbek** [comment]
Having some way to export attachments still would be great. 😉
