### ISSUE TITLE
feature request: add exact search option or allow regex

### ISSUE THREAD

**Issue by jalbstmeijer** [bitwarden/cli#62]
bw list items --search "google account 1"

will now do loose matching, ".\*google account 1.\*"

It would we nice if we could search for exact matches with a command line option or with '\\'"google account 1\\"' too.

**Comment by kspearrin** [comment]
You should be able to accommodate this with piping to something like `jq`.

**Comment by jalbstmeijer** [comment]
ok, in that case something like this.

`bw list items --search "$SEARCH"| jq -r ".[] | select(.name==\"$SEARCH\")"`

**Comment by tukusejssirs** [comment]
Hey, there! Do you know a better way to get a folder ID than the following?

```bash
bw list folders --pretty --search search_key --session $BW_SESSION | jq -r ".[] | select(.name==\"search_key\")" | jq -r .id
```
