### ISSUE TITLE
CLI returns [object Object] when logging in

### ISSUE THREAD

**Issue by Yoshi2889** [bitwarden/cli#64]
When issuing the `bw login` command, entering my e-mail address and then my master password, the CLI client returns `[object Object]`:

![image](https://user-images.githubusercontent.com/1280380/55288977-418b8680-53c0-11e9-993b-a1befe6924d5.png)

When running with the `--response` flag, the response is `{"success":false,"message":"[object Object]"}`.

My account has 2FA TOTP enabled. This is the CLI client version 1.7.2 installed from Homebrew on macOS 10.14.4.

**Comment by blacs30** [comment]
@yoshi2889 do you host bitwarden youself?
I do, using the rust implementation. 
For me with my 2fa enabled account the bw cli asks for the 2fa code after the master password.

**Comment by kspearrin** [comment]
Is this the cloud server? If not, what version is your server?

**Comment by Yoshi2889** [comment]
This is the Bitwarden hosted instance, not a self hosted one.

**Comment by kspearrin** [comment]
I don't have brew setup at the moment, but I was no able to reproduce this issue when isntalling from npm.

**Comment by Yoshi2889** [comment]
I just tried with the NPM version and I get the same issue. Any ideas how I can debug this or gets some more logs?

**Comment by kspearrin** [comment]
Can you check your account in the web vault? Is TOTP the only 2FA provider you have configured?

**Comment by Yoshi2889** [comment]
I have both TOTP and e-mail enabled, according to the website.

**Comment by kspearrin** [comment]
I am not sure. I still cannot reproduce.

![Screen Shot 2019-04-01 at 1 59 22 PM](https://user-images.githubusercontent.com/1190944/55348964-6d713f80-5486-11e9-8ef4-e975884e14e1.png)

Maybe you can try compiling from source and debugging?

**Comment by Yoshi2889** [comment]
I got it to work by resetting the "server" config variable to `bitwarden.com`: `bw config server bitwarden.com`. 

Not sure why that got messed up, but maybe a check to see if the server is valid & up would be nice to avoid cryptic messages like this?

**Comment by kspearrin** [comment]
Great. Thanks for the feedback. We'll see about improving that.

**Comment by rustycamper** [comment]
Please change the error message to something meaningful. Thank you.

**Comment by toastboy70** [comment]
I know this is an old thread but somebody might find this useful: I just saw this same error happening (Ubuntu 18.04 LTS) and updating my client from (from memory) 1.11 to 1.20 fixed it

**Comment by JannikZed** [comment]
I'm still facing this issue on my mac - with TFA enabled .. this error message is really useless.
