### ISSUE TITLE
ssh/gpg agent-like daemon

### ISSUE THREAD

**Issue by seanfarley** [bitwarden/cli#65]
Hi there,

I've been really loving the command-line tool and have been trying to integrate it into my own workflows :-) So, first off, thanks for writing this!

One of the difficulties I've run into while trying to wrap this command-line tool is managing the session key. For instance, if I export the session as an environment variable, then the minute I open a new shell, I no longer have that session variable set.

For the same reason, launching an application (e.g. emacs, vim, qutebrowser, etc) from the macos spotlight doesn't preserve env variables set in another shell.

To work around this, I've written a wrapper script around `bw` that will load the session from a common file (if it exists) and refresh the token if it's already expired. If I didn't centralize this, then every time a process unlocks the vault, the previous session token is no longer valid. This makes it almost impossible to write multiple extensions (e.g. [emacs](https://github.com/seanfarley/emacs-bitwarden), mbsync, and something for qutebrowser) because each one of them fights for getting the session.

Having them all use my own wrapper script means that I can't really publish these extensions in their own right. For the time being, I'm just implementing the session refresh token logic (reading / writing to a file) in each of the extensions but that is very brittle and will break the minute another extension comes along and doesn't do the exact same practice.

Would it be possible to talk about some kind of core capability of an agent running? This would be analogous to how gpg or ssh work (the user unlocks each upon login and they keep running while the user is logged in).

Thoughts?

**Comment by kspearrin** [comment]
I am not sure what the best way to handle this is. We do not want to persist the key to disk by default, which is why we leave that up to the end user. You can always pass the session key in with the `--session <key>` option to each command as well instead of relying on setting the env variable.

**Comment by seanfarley** [comment]
Sorry I wasn't clear before. The `--session` switch suffers from the same problem as having an env variable. Each different extension (really, each process) has to somehow store or communicate the token. Having something like an agent or daemon running would fix that. Or perhaps a webserver (which should be easy in node?) which I found in some prior work [here](https://github.com/birlorg/bitwarden-cli).

**Comment by seanfarley** [comment]
Another alternative would be to specify a label for a session key: e.g. `bw unlock --app emacs` which would allow multiple tokens to be in use. Not sure if that's any better, though.

**Comment by c0sco** [comment]
I had this same problem myself. I ended up creating a tiny bit of code to help solve this problem for bw and other things. Hopefully it will be of use to others. https://github.com/mjslabs/bitagent

**Comment by seanfarley** [comment]
That's really cool! I'll have to check it out soon. For now, I've just implemented everything in emacs lisp 😬

**Comment by cstrahan** [comment]
Another approach:

Login and save the session encrypted with GPG, and then use `gpg-agent` to temporarily cache your password in memory. Then your script can decrypt the session, and if necessary, it will first block waiting for your password via graphical [pinentry](https://gnupg.org/related_software/pinentry/index.html).

This, of course, is only practical if you're already using GPG.

**Comment by danielwagn3r** [comment]
KeePass has a plugin which provides a similar functionality as discussed here, see https://github.com/dlech/KeeAgent

**Comment by xPMo** [comment]
On Linux, `keyctl` can be used to store secrets in-kernel. Here's a simple wrapper I wrote:

```sh
#!/bin/sh
# key is in keyring, can be read, and bw unlock check passes
k=$(keyctl request user bw) && s=$(keyctl pipe "$k") && BW_SESSION=$s bw unlock --check &&
	BW_SESSION=$s exec bw "$@"
# bw unlock succeeds, try and add key
if s="$(bw unlock --raw </dev/tty)"; then
	keyctl add user bw "$s" @u
	BW_SESSION=$s exec bw "$@"
fi
# all else fails, just run bw
exec bw "$@"
```

keyctl is the same mechanism used by ecryptfs. I am not sure if this is abuse of keyctl or not. I wrote another script with gpg but the gpg-connect-agent utility is clunky.

**Comment by ivdimitro** [comment]
@xPMo great tool you have created. I also share the opinion of the author that the usability of the cli is a bit hampered by the current session management. I am trying to use bw cli for the ansible vault password management and without script like yours automation is hard. 
The only thing that will be needed some automation to lock the vault after some period of inactivity.

**Comment by xPMo** [comment]
>  The only thing that will be needed some automation to lock the vault after some period of inactivity. 

```sh
keyctl timeout "$k" 600   # 10 min timeout
```

**Comment by C-Glick** [comment]
@xPMo @ivdimitro I Added some additional features to the wrapper script to suit my own environment. An easy timeout variable, a clear command, and some informative messages. Also added `FORCE_COLOR=3` to the `bw unlock --raw` command to keep the formatting on the password prompt when redirecting stdout to a vairable.

https://github.com/C-Glick/bwu

```bash
#!/bin/sh

#------BitWarden Utilitiy------#

# wrapper script to store bw session value into linux keychain with timeout
# key is in keyring, can be read, and bw unlock check passes
timeout=43200	#how long to retain session key for in seconds 

GREEN='\033[0;92m'
RED='\033[0;31m'
NC='\033[0m' # No Color


if [ $1 = "clear" ]; then
	k=$(keyctl request user bw) && keyctl unlink "$k" 
	bw lock
	printf "${GREEN}Session cleared and vault locked${NC}\n" >&2 
	exit 0
fi


#get key value for session, save into k
#retrieve session value into s
if k=$(keyctl request user bw) && s=$(keyctl pipe "$k"); then
	printf "${GREEN}Unlocked vault with session key${NC}\n" >&2 
	BW_SESSION=$s exec bw "$@"
else
	#could not get session id
	#attempt to unlock, if succssful store session value and execute commad
	if s="$(FORCE_COLOR=3 bw unlock --raw)"; then
        	k=$(keyctl add user bw "$s" @u)
        	keyctl timeout "$k" "$timeout"		#set timout
		timeoutHrs=$(echo "scale=1; "$timeout"/3600" | bc)
		printf "${GREEN}Session key saved for %0.1f hours${NC}\n" "$timeoutHrs" >&2 
        	BW_SESSION=$s exec bw "$@"
	fi
fi

```

**Comment by nikaro** [comment]
I use [rbw](https://github.com/doy/rbw) for this very reason.

**Comment by thetic** [comment]
I am still interested in this feature.

**Comment by dwbit** [comment]
Hey everyone, since this is an ongoing discussion, we'll be closing the issue. The best place to continue the conversation is on the Bitwarden Community Forums. There are several related concepts in the [Feature Requests](https://community.bitwarden.com/c/feature-requests) category.
