### ISSUE TITLE
Impossible to query for the “Not assigned” items of an Organization’s Vault

### ISSUE THREAD

**Issue by pachulo** [bitwarden/cli#66]
Maybe I'm missing something, but with the CLI, I'm unable to query for the items that are in an Organization Vault but assigned to no Collection.

In the Web Vault, I can see them when on the «All Items» section of the Organization, apart from the “Not assigned” “Collection”, but they do not appear when I do:

`$ bw list items --organizationid notnull`

Nor with:

`$ bw list items`

I guessed that they should appear using those, shouldn't they?

**Comment by kspearrin** [comment]
The CLI gives you access to items that your individual account has access to, which is different than what you see from the organization administrator's view in the web vault. This does not include organization items not assigned to collections.

**Comment by pachulo** [comment]
Then, do I have any options to query those items from the CLI?

**Comment by kspearrin** [comment]
No, organization management is not available in the CLI at this time.

**Comment by pachulo** [comment]
OK, will open a feature-request in the forum then. Thanks!
