### ISSUE TITLE
Limit reached at around 1350 entries ?

### ISSUE THREAD

**Issue by mickaelperrin** [bitwarden/cli#68]
Hi,

I have written a tool to migrate our large LastPass secrets database to bitwarden.

The tool hangs at around 1500 entries migrated with the following error message:

    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
     1: 0x1000664d8 node::Abort() [/usr/local/bin/node]
     2: 0x100066b6d node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
     3: 0x10018059b v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
     4: 0x10018053c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
     5: 0x1004439c4 v8::internal::Heap::UpdateSurvivalStatistics(int) [/usr/local/bin/node]
     6: 0x100449ae4 v8::internal::Heap::SetUp() [/usr/local/bin/node]
     7: 0x10042a129 v8::internal::Factory::AllocateRawWithImmortalMap(int, v8::internal::PretenureFlag, v8::internal::Map*, v8::internal::AllocationAlignment) [/usr/local/bin/node]
     8: 0x10042b9e1 v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
     9: 0x10050adc1 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
    10: 0x1001940ff v8::String::Utf8Length(v8::Isolate*) const [/usr/local/bin/node]
    11: 0x10004d08e node::Buffer::(anonymous namespace)::ByteLengthUtf8(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
    12: 0x1001e4024 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
    13: 0x1001e363e v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
    14: 0x1001e2e7b v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
    15: 0x2379e214fc7d

Now nothing works, the web gui and the mac applications seems to try loading entries but finally fails with a blank vault.

Even the CLI sync fails, and the local data.json contains no ciphers only keys.

Have I reached the limits of Bitwarden ???

**Comment by kspearrin** [comment]
There is no vault item storage limit, so there is something else breaking for you. We have users with many more items than that. With the desktop application, for example, are there any errors listed in the console if you do View > Developer tools?

**Comment by mickaelperrin** [comment]
@kspearrin Thanks for your quick answer, I have opened an issue directly on the web vault repository.

For paid users, is opening issues here is the right workflow, or should I use another channel ?

**Comment by kspearrin** [comment]
Closing since the new issue was opened.
