### ISSUE TITLE
Scripting and command subsitution input prompts not showing

### ISSUE THREAD

**Issue by kwkelly** [bitwarden/cli#7]
I'm trying to script in bash with the bitwarden cli, but I'm having some issues trying to login or unlock within a command substitution. Within a command substitution, the prompts do not show up.

For example: `bw unlock --raw` works just fine, but if I try to capture that output, no prompts show up. So `session=$(bw unlock --raw)` won't ask for the password.

I think it may be an issue with inquirer.js, so I also filed an issue with them [here](https://github.com/SBoudrias/Inquirer.js/issues/681).

**Comment by adihrustic** [comment]
I'm experiencing the same problem. I'm able to type in my password and unlock the vault, but there's no prompt showing up

**Comment by kspearrin** [comment]
We'll have to see what the inquirer devs say since it's definitely a problem there. Not sure if it's possible with what you are trying to do (I'm guessing not since you are probably persisting this script on disk), but you can also pass in your password an argument to `bw unlock [password]`

**Comment by adihrustic** [comment]
I mean, it still works fine. It just looked neater with the asterisk's :frowning_face:

**Comment by kwkelly** [comment]
@adihrustic It actually doesn't work for me since all the output (including the prompt) from `bw unlock --raw` gets passed into the variable, so it looks like this

```
> session=$(bw unlock --raw)
> echo $session
? Master password: ******** NtHhkWyWtjnm9TVUhnN2LWItgRWewh5e5vIDca+zlT0fzLUmXAPV+fayqzSEV1+E4BQ6a9eySypUvUDHLX6IJw==
```

@kspearrin Correct, I don't want to persist the password in plaintext on disk, but isn't passing the password as an argument a risk anyway, since then the password shows up in history and the output of `ps`.

**Comment by adihrustic** [comment]
@kwkelly 

Key seems to always end with "==". Use regex:

`echo $(bw unlock --raw | grep -o .*==$)`

**Comment by kwkelly** [comment]
@adihrustic I think that will work for me, thought it's a bit of a hack.

Interestingly, [the bash builtin `read` uses stderr to display the prompt text](http://git.savannah.gnu.org/cgit/bash.git/tree/builtins/read.def). Redirecting stderr to stdout causes it to be captured in the variable.

**Comment by kwkelly** [comment]
From [another issue over at inquirer.js](https://github.com/SBoudrias/Inquirer.js/issues/519), it is indeed possible (and proper in some cases) to use stderr for the prompt, like so:

`inquirer.createPromptModule({ output: process.stderr })`

I can get that to work in a quick test script just fine, but when I try to update the unlock command, I get a build error saying 0 arguments were expected, but that it got 1 for the `createPromptModule` function.

**Comment by Mange** [comment]
Correct! Stderr is not for errors but for all text that should be visible for an operator while doing some sort of operation. Stdout is for machine-readable output, so prompts should always be on stderr.

**Comment by edouardmenayde** [comment]
Where are we on this ? I would love to be able to use it with my scripts

**Comment by kwkelly** [comment]
So what needs to happen is that the DefinitelyTyped package for inquirer.js (in here:  https://github.com/DefinitelyTyped/DefinitelyTyped ) needs to be updated since the type definition for createPromptModule does not include the optional arguments. Then Bitwarden can be updated to use stderr for prompts without a type error on compilation. I’ve been meaning to do it but have been busy

Apologies for typos and poor formatting — I’m on my phone

**Comment by kspearrin** [comment]
@kwkelly I can actually cast `inquirer as any` to avoid any typing. Do you know what options I need to use to fix this? Code sample?

**Comment by kwkelly** [comment]
@kspearrin I created a pr with the changes you suggested. I still think the _right_ way to do it is to update the type definitions though.

https://github.com/bitwarden/cli/pull/14

**Comment by kwkelly** [comment]
I've submitted a [PR to DefinitelyTyped to allow specifying the input and output streams for inquirer](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26623). If that gets merged then the cast to any can be removed to allow type checking.

**Comment by kspearrin** [comment]
@kwkelly Thanks. I'll wait and see if the typings get updated soon. If not, I'll accept the PR here as is.

**Comment by kwkelly** [comment]
@kspearrin the new type definitions have been merged and I made the associated changes and pushed them to the fork. The merge request should now be using the head commit with the new types.
