### ISSUE TITLE
Permission denied when installed using Snap

### ISSUE THREAD

**Issue by tetienne** [bitwarden/cli#71]
**OS**: Ubuntu 18.04

```
❯ snap install bw
bw 1.7.4 from 8bit Solutions LLC (bitwarden✓) installed
```

Whatever the command, I got the following error:

```
❯ bw --help
fs.js:145
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/home/tetienne/.config/Bitwarden CLI'
    at Object.fs.mkdirSync (fs.js:874:3)
    at mkdirpSync.targetDir.split.reduce (/snapshot/cli/build/bw.js:17479:42)
    at Array.reduce (<anonymous>)
    at Function.mkdirpSync (/snapshot/cli/build/bw.js:17476:48)
    at new lowdbStorage_service_LowdbStorageService (/snapshot/cli/build/bw.js:17500:37)
    at new bw_Main (/snapshot/cli/build/bw.js:23450:31)
    at Module.<anonymous> (/snapshot/cli/build/bw.js:23520:14)
    at __webpack_require__ (/snapshot/cli/build/bw.js:21:30)
    at /snapshot/cli/build/bw.js:85:18
    at Object.<anonymous> (/snapshot/cli/build/bw.js:88:10)
```

Apparently, the permissions given to the snap package are not enough to write withon home folder.

**Comment by kspearrin** [comment]
I just tested this on Ubuntu 18.04 and was not able to reproduce.

I am also not sure why your is trying to create something in `/home/tetienne/.config`. Snap data should be coming from `/home/tetienne/snap/bw/xx/.config`

**Comment by tetienne** [comment]
Sorry I miss your answer. I test it again on my machine and I can still reproduce. About the path in the error, I didn't do anything particular. Only the `snap install bw` and then any `bw` command.

**Comment by TheRealDannyBoy** [comment]
I am experiencing this same error on openSUSE Tumbleweed.

**Comment by ioanrogers** [comment]
I had this issue, and it was because I was setting `$XDG_CONFIG_HOME` in my bash config. This was apparently overriding whatever `snap` itself wants to use. So I don't think it's an issue with the snap packaging of this app, maybe more of a thing to be aware of with snaps in general.

**Comment by ob211** [comment]
I am getting this error on a fresh install of Lubuntu.

**Comment by TheRealDannyBoy** [comment]
> I had this issue, and it was because I was setting `$XDG_CONFIG_HOME` in my bash config. This was apparently overriding whatever `snap` itself wants to use. So I don't think it's an issue with the snap packaging of this app, maybe more of a thing to be aware of with snaps in general.

That's unfortunate.  Although I don't actually change the storage location, I do need to set that variable for certain apps to be aware of it.

**Comment by tetienne** [comment]
@ioanrogers It means probably bw has to read this variable too.

**Comment by daniprado** [comment]
Workaround: `ln -s ~/snap/bw/current/.config/Bitwarden\ CLI ~/.config/Bitwarden\ CLI `
I agree that being forced to not give a value (or even a fixed one) to `$XDG_CONFIG_HOME` is not acceptable...

**Comment by ewjoachim** [comment]
Fresh ubuntu install, I had to do the following for it to work:
```
mkdir -p '/home/joachim/snap/bw/current/.config/Bitwarden CLI'
ln -s ~/snap/bw/current/.config/Bitwarden\ CLI ~/.config/Bitwarden\ CLI 
```
