### ISSUE TITLE
bw login: only output login command to stdout

### ISSUE THREAD

**Issue by nmattia** [bitwarden/cli#74]
Right now there's a bunch of stuff being output to stdout when performing a `bw login`. It'd be great to have everything written to stderr _except_ for `export BW_SESSION=...` so that one can run `$(bw login)` without having the session token be written in bash's history.

For a workaround, ` export BW_SESSION=...` (note the space at the beginning).

**Comment by kspearrin** [comment]
Use the —raw option. See https://help.bitwarden.com/article/cli/#session-management

**Comment by nmattia** [comment]
Thanks!
