### ISSUE TITLE
Login fails with ECONNRESET

### ISSUE THREAD

**Issue by henrebotha** [bitwarden/cli#79]
I'm trying to do `bw login $EMAIL`. A fraction of a second after entering my password, I get this error:

```
request to https://api.bitwarden.com/accounts/prelogin failed, reason: read ECONNRESET
```

I'm sitting behind a corporate proxy, so my immediate assumption is that that is the problem (as has been the case for many command-line tools). I have proxy values configured in various different locations depending on the tool in question (environment variables, per-tool config files, etc), but I can't figure out which underlying tool `bw` is using to make the API call.

**Comment by kspearrin** [comment]
Are you using HTTP_PROXY and HTTPS_PROXY environment variables?

**Comment by henrebotha** [comment]
Yup.

**Comment by kspearrin** [comment]
Seems we need to make some changes to support a proxy with node-fetch:

https://github.com/bitinn/node-fetch/issues/79

**Comment by kspearrin** [comment]
Maybe fixed with https://github.com/bitwarden/jslib/commit/bc5a6e02c106dc87413f22b7c7cb0334c1fc6e88

Can you try the latest dev build? Binaries are built here:
https://ci.appveyor.com/project/bitwarden/cli/build/job/mcd80pf4yvjnr3x5/artifacts

**Comment by henrebotha** [comment]
Working!

**Comment by kspearrin** [comment]
Great. Will be officially available whenever the next release happens.
