### ISSUE TITLE
Login don't show password *

### ISSUE THREAD

**Issue by masterwendu** [bitwarden/cli#8]
At least in Linux it's not common to show * when you type in a password (I think this is for safety reasons)

So I would recommend to change the password input at the login to an input which doesn't show the *

**Comment by jcrben** [comment]
If I type `bw login` I get a prompt which looks like this:
![image](https://user-images.githubusercontent.com/5614134/41503013-1c42f7f8-717d-11e8-85e7-ec43c5b7d2e5.png)

**Comment by kwkelly** [comment]
@kspearrin what are your thoughts on this? I can make the changes and submit a PR if you like the idea to change this.

Essentially the `mask` option when creating the prompt just needs to be changed.

**Comment by kspearrin** [comment]
I’m ok with it masking on macOS and Linux. Not sure if this is common on windows environments too.
