### ISSUE TITLE
Accessing securenote

### ISSUE THREAD

**Issue by macgeekpro** [bitwarden/cli#81]
Hi! I have been trying access my secure note via the cli but have been unable to do so. Is the secure note accessible? if so, can anyone share a pointer on how I can do that?

**Comment by kspearrin** [comment]
Yes, secure notes are available in the CLI, just like any other vault item. You should see it available with `bw list items`.

**Comment by macgeekpro** [comment]
Found it. Thanks for the pointer.

**Comment by ironhouzi** [comment]
Is it possible to get the value without parsing JSON? I was hoping for something like:

```sh
bw get notes 'gitlab access token'
```

Just like you can easily fetch the password value..

I've re-read the docs, and searched the internet without anything helpful.
