### ISSUE TITLE
U2F support in CLI

### ISSUE THREAD

**Issue by mboes** [bitwarden/cli#82]
The CLI (as of v1.7.4) does not support Yubikeys via U2F:

```
$ bw login foo@example.com
? Master password: [hidden]
No providers available for this client.
```

This makes the CLI basically unusable for me (OTP is annoying to enable because I keep on brushing the key's button by mistake when typing). As noted in #39, it's possible that support is easy to add since the auth.service jslib already claims to support U2F as a two-factor provider type.

Related: #39.

**Comment by kspearrin** [comment]
I am not aware of a way to easily support U2F in non-browser environments, such as a CLI.

**Comment by iKarith** [comment]
Possibly apropos:

https://developers.yubico.com/yubihsm-shell/
ashtuchkin/u2f-client

The latter looks like exactly the thing you're looking for.
