### ISSUE TITLE
return the result without quote

### ISSUE THREAD

**Issue by pascalandy** [bitwarden/cli#83]
### Context

I have a simple question. From [this example](https://help.bitwarden.com/article/cli/#working-with-json), when I do this CMD I get this result:

```
bw get item token_test | jq '.notes'

"rGAERGQ34G"
```
### Question

How do I get the result without the double quote? I know I can stripe it with `awk`, `sed`, `cut` but I want to keep the query as small as possible.

Thanks!

**Comment by StephenBrown2** [comment]
`"-r"` or `"--raw-output"` isn't too far down the [jq manual](https://stedolan.github.io/jq/manual/) page.

For your example, it would be:
```shell
$ bw get item token_test | jq -r '.notes'
rGAERGQ34G
```

**Comment by pascalandy** [comment]
Thanks a lot @StephenBrown2! Very appreciated :)

I didn't knew where to find `jq`s docs :-p
