### ISSUE TITLE
feature request: make CLI to use full-text search

### ISSUE THREAD

**Issue by Levenson** [bitwarden/cli#86]
Is there any plans to implement the same search for CLI as Web vault, browser extensions and desktop apps have? 

Here is my workflow which doesn't work well. I do have a workaround though. 

I currently create some item, give it a regular name and then add uris to it. I am using emacs and emacs-bitwarden extension, which uses bitwarden-cli tool to search for items. 

Some items can have names which are not related to the actual URL. For example, I have a corporate Outlook email account, but use davmail for this. It runs on my localhost and exposes regular services like IMAP, SMTP, etc.

It still requires me to authorize every connection using my corporate account thought.  

My item (example.com) has URL localhost:2025. My email configuration looks something like this:

```
smtpmail-smtp-server "localhost"
smtpmail-smtp-service 2025
```

Which basically expands into  

```
bw list items --search "localhost"    
```
And of course, it doesn't return my example.com item. I haven't found any requests for this, so I created it. 

PS: Thanks for the bitwarden

**Comment by kspearrin** [comment]
The search does look at the URL, but only the first one. So if you have multiple URLs and localhost is not the first, it would get missed. Is that the case here?

**Comment by Levenson** [comment]
Yes, in my case, my employer uses Microsoft, so I have couple of links from it's domain, a bunch of Microsoft urls, android:// urls, and davmail itself exposes multiple services like imap, smtp and caldav.
