### ISSUE TITLE
bitwarden-cli outputs extra newline on linux

### ISSUE THREAD

**Issue by operator-name** [bitwarden/cli#87]
On linux running a bitwarden command outputs an extra newline. The relevant prices of code are as follows:

[utils.ts#L13](https://github.com/bitwarden/cli/blob/master/src/utils.ts#L13`)  
[jslib/baseProgram.ts#L54](https://github.com/bitwarden/jslib/blob/b74ee7b3ee823a820854623cc32c8522a09e9f4d/src/cli/baseProgram.ts#L54)

This is annoying when relying on the output in a script, and can be confusing if a passphrase ends with a newline. It seems that this was fixed for windows by this commit: https://github.com/bitwarden/cli/commit/24cb2b0cdbe59898cfc76776e9ab9613180e6db0 

Is there any reason this change cannot be made for linux? I'm assuming the change was made as some linux terminals/ps1 configurations don't output a newline like windows does. In this case I propose to check if the output is a [tty](https://nodejs.org/api/tty.html#tty_writestream_istty) and output a newline accordingly, which I'm happy to do.

**Comment by kspearrin** [comment]
My observation was that my Linux terminal (Ubuntu) was not adding a new line and caused some weird issues with the next input line of the terminal after running a `bw` command. This wasn't the case on Windows, which is why you see the solution you discovered.

I am not an expert on Linux command-line interfaces, so if you are saying there is a more intelligent way to detect this, I'd be open for a PR.

**Comment by operator-name** [comment]
It's my understanding that your linux terminal is working as expected, and the workaround although user friendly hides an issue with your configuration instead of solving it.

I'd assume your `$PS1` doesn't include a newline at the start - the debian/ubuntu default is:  
`PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '`  
whereas mine is  
`PS1=\n\[\033[1;32m\][\[\e]0;\u@\h: \w\a\]\u@\h:\w]\$\[\033[0m\]`  

You should find that other programs on linux (`printf` for example) also don't output a newline on your configuration. The issue comes about when scripting - for example if you pipe the output of `bw` to a file or a different program that simply reads the newline as part of the password.

Personally I think the "correct" thing to do is to revert the change and add some documentation about adding a newline to the `$PS1`, but a "soft" solution would be to detect if it is outputting to a terminal or not. I don't have a strong opinion here as either solution fixes my use case but I think it's your call.

**Comment by kspearrin** [comment]
>  but a "soft" solution would be to detect if it is outputting to a terminal or not

Is this the TTY check you mentioned previously?

**Comment by operator-name** [comment]
That's right, as you can see the change is very simple.

**Comment by kspearrin** [comment]
Thanks. Merged.
