### ISSUE TITLE
mac failed: when trying to make query to bw cli

### ISSUE THREAD

**Issue by RakibFiha** [bitwarden/cli#88]
Can anyone help me, I am having the following issue with bw-cli.
Whenever I try to make any kind of query or request to bw cli I keep getting this mac failed error. I am using Ubuntu 18.04
```
💲 bw get password namep --session $session
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
123456
````
Exit status:
```
💲 echo $?
0
```
Current version:
```
💲 bw -v
1.7.4
```

**Comment by kspearrin** [comment]
Is your session key correct?

**Comment by RakibFiha** [comment]
Yes, it's correct, I get always get the correct result at the end which is 123456 in this case. But, before that, I keep getting `mac failed`. One way I am avoiding this is just by simply redirecting the stderr to /dev/null
```
myPass=$( bw get password namep --session $session 2>/dev/null )
```
But, it's not a good solution.

**Comment by kspearrin** [comment]
Looks like you've got a few items in your vault that are corrupted or something.

If you log into the web vault, so you see the same mac failed error messages in the console?

**Comment by RakibFiha** [comment]
I don't see this error happening anywhere else besides terminal.

**Comment by kspearrin** [comment]
Did you figure it out?

**Comment by RakibFiha** [comment]
I found some attachments missing their file names as you have suggested.
I deleted them and mac failed has gone! thank you for pointing it out.

**Comment by robin-snt** [comment]
I'm having this exact same issue on version `1.21.1`. Really rough to deal with as I have so many entries and going through each entry in the web client seems really cumbersome. It would benefit the user tremendously if the error message contained the UUID of the entry it errors on, so one knows exactly what entries are causing the error.

Also, muting stderr is not acceptable as that would mute valid messages for ambiguous queries.
This is just weeks before I'm giving a presentation to my colleagues on bitwarden CLI, so I really hope this gets sorted out in time.

**Comment by eliykat** [comment]
Hi @robin-snt, is it the issue described in this thread? https://github.com/bitwarden/cli/issues/490
Does clearing your data.json (as described [here](https://github.com/bitwarden/cli/issues/490#issuecomment-1054769524)) fix it?

We're working on fixing #490 (assuming it's one of the issues described in there), but if it's not fixed before your presentation, you can always downgrade to the previous version.

**Comment by robin-snt** [comment]
Perfect! Deleting the locally cached data file did solve it.
