### ISSUE TITLE
Self signed certificate support

### ISSUE THREAD

**Issue by paescuj** [bitwarden/cli#9]
Since Node.js uses a built-in certificate store, I have to use the following workaround the get the CLI working with my self signed certificate:
```bash
NODE_EXTRA_CA_CERTS=<path to my ca> bw login
```

There should be an option (e.g. config setting, specific environment variable, ...) for the CLI to permanently trust a self signed CA.

**Comment by kspearrin** [comment]
I don't plan to change this. You can easily use the node cert store as explained.
