### ISSUE TITLE
Feature request: Allow downloading of the encrypted vault from server without entering master password

### ISSUE THREAD

**Issue by fuxoft** [bitwarden/cli#91]
Currently, the master password has to be entered in order for the up-to-date encrypted vault to be downloaded. The entered password is hashed and the hash is sent to the server to authenticate the user.

I think it would be beneficial to have an option to enter only the password hash when logging into bw, not the password itself. This would allow e.g. for non-interactive scripted downloading of the encrypted vault without storing your master password anywhere in the script.This way, if your security is breached, the attacker would get access to your encrypted vault but won't be able to decrypt it, which is acceptable security / ease of use tradeoff for me.

I wanted to create a script that automatically downloads and backs up my (encrypted) vault every night so that I can go "back in time" to previous vault version in the case I accidentally delete some important passwords. But the current CLI implementation does not allow for downloading the (encrypted) vault without exposing my full master password in the downloader script, although I don't want to decrypt the vault at any point during this process.

**Comment by quitequick** [comment]
+1

**Comment by alxpy** [comment]
+1

**Comment by doge-gif** [comment]
+1 too

**Comment by IpsmLorem** [comment]
Like https://github.com/bitwarden/cli/issues/91

**Comment by eliykat** [comment]
This has also been requested in #232, which has more detailed discussion, so I'll close this Issue as the duplicate. Please continue any discussion in #232.
