### ISSUE TITLE
Export feature is complicated and not exporting from organizations

### ISSUE THREAD

**Issue by r7l** [bitwarden/cli#92]
When using the `export` option of the CLI tool, it does not export any of the passwords i have within an organization. I can see those encrypted in `data.json` file but it won't export any of it. Please add this feature. The CLI export is pretty much useless for me this way.

I am only using Bitwarden since it was introduced by a fellow co-worker to our company. Since we are about to move our passwords to Bitwarden now, it lacks some way to automatically pull backups from it.

I thought it would be possible with the CLI tool but instead it's not. The other thing i've noted is that it's really hard to even do backups with the CLI as you have to login, get a session token, you need to remember and put behind any other command you run and you also need to enter a second password when finally exporting.

It would help allot of some could simply run one command that logs in, exports everything and logs out after it as this would be the most likely scenario for anyone planing to do scripted backups once in a while.

**Comment by kspearrin** [comment]
Added to next version of the CLI (can test dev build if you like):

```
be export <password> --organizationid <orgid>
```

**Comment by r7l** [comment]
Thanks
