### ISSUE TITLE
Feature request: read config values

### ISSUE THREAD

**Issue by matbech** [bitwarden/cli#94]
Right now it is possible to set the config value using the config setting value command:
https://help.bitwarden.com/article/cli/#config

It would be helpful to have a way to read the config values. For example, I would like to know what the current configured server url is.

The config command could probably just output the value if no value is specified in the command line. Syntax:
`bw config <setting>`

**Comment by kspearrin** [comment]
What about:

```
bw get config <setting>
```

?

**Comment by matbech** [comment]
My understanding is that the get command gets data from the vault. I'm not sure where configuration data is stored, but I do assume it is not encrypted because it must be available before the value is unlocked.

**Comment by kspearrin** [comment]
Added for next version:
https://github.com/bitwarden/cli/commit/492bc32aa31c5957bd3d6b57ac7f1d144bcfbfa7
