### ISSUE TITLE
bw get item <item name> returns 'not found'

### ISSUE THREAD

**Issue by magick93** [bitwarden/cli#95]
Hello

I'm fairly new to both bitwarden and the bw cli.

I am using an onprem bitwarden installation, and have logged in. 

I have created one item - using the web interface - called `test1`. It is the only item for my user.

I then try to retrieve this using `bw get item test1` but it returns `Not found.`

What might I be doing wrong?

**Comment by kspearrin** [comment]
Did you `bw sync` before trying to `bw get` it?

**Comment by magick93** [comment]
Perfect! That did it.

What does sync do in the background? Is it populating a local database?

**Comment by kspearrin** [comment]
Yes, all Bitwarden apps sync the data down from the server to the local database. This happens automatically when using most Bitwarden clients, but with the cli you have to perform this command on your own.

**Comment by magick93** [comment]
> all Bitwarden apps sync the data down from the server to the local database.

What kind of database is it? And is the data encrypted?

**Comment by kspearrin** [comment]
This should help https://help.bitwarden.com/security/
