### ISSUE TITLE
Feature request - set id OR unique item names

### ISSUE THREAD

**Issue by magick93** [bitwarden/cli#98]
Hi

# User story
As a devops engineer, I'd like to automate the creation on passwords, in an idempotent way, so that the script can be run multiple times without changing the state

# Example - create item

If I run the following 3 times, I get three different items created, even though I have specified an identical id, and identical name:

`bw create item eyJvYmplY3QiOiJpdGVtIiwiaWQiOiJteS1jdXN0b20taWQiLCJvcmdhbml6YXRpb25JZCI6bnVsbCwiZm9sZGVySWQiOiI4OWVkZDM2NC0xMmUzLTQzZGQtYTlkZC1hYWU4MDAyYzE3OTQiLCJ0eXBlIjoxLCJuYW1lIjoiY3VzdGlkIiwibm90ZXMiOm51bGwsImZhdm9yaXRlIjpmYWxzZSwibG9naW4iOnsidXNlcm5hbWUiOiJ1c2VybmFtZTEyMyIsInBhc3N3b3JkIjoiYWJjZCIsInRvdHAiOm51bGwsInBhc3N3b3JkUmV2aXNpb25EYXRlIjpudWxsfSwiY29sbGVjdGlvbklkcyI6W10sInJldmlzaW9uRGF0ZSI6IjIwMTktMTAtMThUMDA6MjY6MTAuMDIzWiJ9`.

After running the command, the command returns with a json result.

## Retrieving items.

When I run `bw get item custid` I get a non-json result that shows there are several items with the same name.

# Current solution

It seems the only way to create a unique item requires addressing the following issues:

- In the case where more than one item exists with the same name, need to do some ugly string parsing as the result isnt json
- In the case where there is no items returned for the search name/phrase, the result is `Not found.` which also requires text parsing as it isnt json
- During creation, need to somehow keep track of created id - this requires some addition state management / database

# Better solution

- It would be so much easier if names where unique, or if the ID could be set at creation time. What is the use-case for having non-unique item names?
- Be consistent with return values - some are in json, some arent. Perhaps let the operator decide. For example, perhaps have a `-o json` option.
- The folder and item concept is, I assume, inspired by file systems - which most people are familiar with. One core concept in filesystems is that files in a folder must have unqiue names. Likewise with folders. This is a concept that most everyone is familiar with.

**Comment by kspearrin** [comment]
I'd think the proper way to do this would be to first check if the item exists by name using the `get` command. If so, use `edit`. If not, use `create`.

**Comment by magick93** [comment]
Unfortunately that doesnt work because:

- `bw edit item test` expects a json input. It errors with `requestJson was not provided.` It expects a "object id".
- client apps still need to maintain a separate database of ids to map to bitwarden, as bitwarden is incapable of allowing user-defined unique entries.

**Comment by kspearrin** [comment]
@magick93 You'd have to parse the resulting JSON from the `get` command and pipe that into the edit command, along with it's id.

You could use a custom field to provide your user defined id. If you did this, you'd have to locate the matching item using the `list` command.

**Comment by magick93** [comment]
> You'd have to parse the resulting JSON from the `get` command

This is another example of not returning json. When I run `bw get item test` I get:

```
More than one result was found. Try getting a specific object by `id` instead. The following objects were found:
d3fbef8e-4b49-4f2d-b5da-aae8003304a9
6b87f98f-be92-4f58-a9d7-aae8015a7b07
d5b38337-2ff9-4afc-a4d1-aae80178d517
```

**Comment by kspearrin** [comment]
Can you use `--raw` or `--response` options?

**Comment by magick93** [comment]
When I use `--raw` I get the default response type.

When I use `--response` it does return json, however the list of items isnt an array - its just a string with line breaks:
```
{"success":false,"message":"More than one result was found. Try getting a specific object by `id` instead. The following objects were found:\n5f830a35-319f-4692-9e46-aaec017c69a3\n2f9fb018-d479-40c4-a271-aaec017c6246\nd3fbef8e-4b49-4f2d-b5da-aae8003304a9\n6b87f98f-be92-4f58-a9d7-aae8015a7b07\nd5b38337-2ff9-4afc-a4d1-aae80178d517"}
```

**Comment by magick93** [comment]
> You could use a custom field to provide your user defined id.

Yeah ok, but this means:

1. I'd need to manually search through all items to find the custom defined id
1. There is the possibility of a race condition as, if I forget to run `bw sync` or even if I do, but another operator adds an item in the meantime, the result I get will not be accurate.

**Comment by magick93** [comment]
Besides the `id` field, are there any fields that are unique?

If not, then I dont see how users can - with confidence - create unique items.

**Comment by kspearrin** [comment]
For next version, I added the id array to the `data` property of the error response.

You can use the `--response` option and get the following:

```
{"success":false,"message":"More than one result was found. Try getting a specific object by `id` instead. The following objects were found:\n3303a01d-1228-408f-98ee-a9d1016bd47d\neff78d47-3111-4875-8f74-aa95012fbb84","data":["3303a01d-1228-408f-98ee-a9d1016bd47d","eff78d47-3111-4875-8f74-aa95012fbb84"]}
```



> 
> 
> Besides the `id` field, are there any fields that are unique?
> 
> If not, then I dont see how users can - with confidence - create unique items.

No, the `id` field is the only unique identifier. It is generated and assigned by the server.

**Comment by bborysenko** [comment]
Stuck with the same issue, while trying to create organization collections. The create command should return the `id` of created object to be able reference to the object. For the moment (1.8.0 version) this is always `null`:

```
{"object":"org-collection","id":null,"organizationId":"xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","name":"Test","externalId":null,"groups":[]}
```

> For next version, I added the id array to the data property of the error response.

When can we expect the next version?

**Comment by kspearrin** [comment]
@bborysenko No ETA at the moment, but you can try the latest dev builds here: https://ci.appveyor.com/project/bitwarden/cli/build/job/mk26v4wkx3j70jsr/artifacts

**Comment by tjyang** [comment]
Hi @kspearrin 

I need BW server to have ability to disallow duplicated item name. It doesn't have to be enabled by default.

**Comment by cscharf** [comment]
Hi @tjyang , we now use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one. There is already a feature request for unique item names as well: [https://community.bitwarden.com/t/restrict-item-names-being-unique/8561](https://community.bitwarden.com/t/restrict-item-names-being-unique/8561)

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This appears to have been addressed, to some degree, based on the multiple options of implementation/satisfaction of the requested user story. This issue will now be closed. Thanks!

**Comment by magick93** [comment]
> This appears to have been addressed, to some degree, based on the multiple options of implementation/satisfaction of the requested user story.

I'm not sure what the multiple options that you're referring to are. The [feature request](https://community.bitwarden.com/t/restrict-item-names-being-unique/8561) doesnt show any workarounds for this issue.

**Comment by cscharf** [comment]
The requested user story proposed multiple options to solve for it, and the workaround presented was to use the `id` instead of `name` for uniquely identifying distinct items.

**Comment by magick93** [comment]
> the workaround presented was to use the id instead of name for uniquely identifying distinct items.

Its a "workaround" - that is, an ugly solution.

Bitwarden uses a pseudo file and folder structure - see https://bitwarden.com/help/article/folders/

Can you name one fileystem that allows you to create files with the same name? Or requires you to use custom fields to store an `id`, and then requires you to look up that id to make sure your not create a new file with the same name?

I didnt propose solutions to solve it, I pointed out what is wrong, and I and others have showed ugly workarounds. Its hardly solved.

**Comment by cscharf** [comment]
I completely understand, however we use GitHub for issues/bugs and this is considered an enhancement/change request for our current product and is already being tracked in our community forums. Please feel free to upvote as we continually evaluate our roadmap and development priorities based on community needs/demands.

Believe me, I'm not saying we want to ignore this, we're simply tracking it in another location ;-) You are not alone.

**Comment by tjyang** [comment]
Please upvote https://community.bitwarden.com/t/restrict-item-names-being-unique/8561, currently it only has one vote from me.
