### ISSUE TITLE
Feature request: fallback when bw can't process a command

### ISSUE THREAD

**Issue by quilicicf** [bitwarden/cli#99]
Hi, 

I've switched to bitwarden recently and started using the CLI a lot. I noticed one UX improvement that IMO could benefit all users. 

When running a command that bw is not able to process, the command exits and one has to retry. Examples:

1. `bw get item myItem` with vault locked
1. `bw get totp git` whith multiple git accounts saved in the vault

I think it would be better to ask for the missing information rather that quitting and letting the user do the work. In my examples that would mean:

1. bw would ask for the master password and unlock the vault before going on and retrieving `myItem`
1. bw would show a list of all TOTPs that match the search and let the user choose the one they want

What do you think? 

I'd be happy to help! I've currently circumvented this with utility methods in my `.bashrc` but it'd be way better to let the community profit from this. 

And hacktoberfest is on :laughing:

**Comment by kspearrin** [comment]
I added a prompt for unlocking on all actions that require unlock and the session key is not provided. See https://github.com/bitwarden/cli/commit/e7450d27e468f0e68fe5b75f9c52ffa952185484

**Comment by quilicicf** [comment]
That's nice thanks :) 

What about the second item? Does it make sense to you?

**Comment by kspearrin** [comment]
It does, but I don't have a good solution at the moment.

**Comment by quilicicf** [comment]
Couldn't bw show a list of available options (inquirer does that nicely) displayed by name?
With inquirer's autocomplete plugin it'd be really nice to use.

**Comment by kspearrin** [comment]
Yes, that could potentially a solution.

**Comment by quilicicf** [comment]
If I can help you can point me to where this should be done. 
Can submit a PR.
